<script setup lang="ts">
import {computed,onMounted,onUnmounted,ref} from 'vue';
import {Flame,Plus,Search,Monitor,Play,Square,ArrowLeft,ChevronRight,Settings2,Blocks,Users,BookOpen,ScrollText,Link,Copy,Check,RefreshCw,FolderOpen,Download,ShieldCheck,KeyRound,Sun,Moon,X,Minus,ExternalLink,TriangleAlert,Wifi,LoaderCircle,LogOut} from 'lucide-vue-next';
import {invoke} from './bridge';
import type {Instance,State,Room,Invite,Theme,RPCMethod} from '../types';
const native=!!window.emberDesktop;
const state=ref<State>({launcher_version:'0.2.0-beta.1',root:'',platform:'Windows x64',instances:[],tasks:[]});
const search=ref('');const selected=ref<string|null>(null);const tab=ref('overview');const modal=ref<'create'|'invite'|null>(null);const loading=ref(false);const error=ref('');const toast=ref('');
const rooms=ref<Room[]>([]);const room=ref<Room|null>(null);const guests=ref<Invite[]>([]);const logs=ref<string[]>([]);const settings=ref<Record<string,any>>({});const changes=ref<Record<string,string>>({});
const theme=ref<Theme>((['ember','moonlit','light'].includes(localStorage.getItem('ember-desktop-theme')||'')?localStorage.getItem('ember-desktop-theme'):'ember') as Theme);
const create=ref({name:'我的余烬酒馆',port:8180,lan:true});const roomTitle=ref('');const identity=ref('');const issued=ref<Invite|null>(null);const connection=ref({name:'',port:8180,lan:true,channel:'bundled'});
let timer:ReturnType<typeof setInterval>;let toastTimer:ReturnType<typeof setTimeout>;
const active=computed(()=>state.value.instances.find(item=>item.id===selected.value));const filtered=computed(()=>state.value.instances.filter(item=>item.name.toLowerCase().includes(search.value.toLowerCase())));
const busy=computed(()=>loading.value||active.value?.status==='busy');const running=computed(()=>active.value?.status==='running');
const statusLabel:Record<string,string>={running:'运行中',ready:'已安装 · 待启动',not_installed:'待安装',busy:'任务进行中',error:'需要关注'};
const tabs=[{id:'overview',name:'实例概览',icon:Monitor},{id:'rooms',name:'房间与同伴',icon:Users},{id:'plugins',name:'插件管理',icon:Blocks},{id:'settings',name:'API 与配置',icon:Settings2},{id:'logs',name:'运行日志',icon:ScrollText}];
const settingGroups=[{title:'世界知识 · Gemini',note:'双模型主持的知识侧；密钥只传本机部署引擎。',fields:[['GEMINI_API_KEY','API Key','password'],['GEMINI_MODEL','模型','text']]},{title:'决策模型 · OpenAI-compatible',note:'选择你实际可用的模型。配置成功不代表余额或联网已验证。',fields:[['DECISION_API_KEY','API Key','password'],['DECISION_BASE_URL','接口地址','url'],['DECISION_MODEL','模型','text']]},{title:'服务端 TTS',note:'浏览器朗读不需要此配置；服务端生成可能收费。',fields:[['TTS_API_KEY','API Key','password'],['TTS_BASE_URL','接口地址','url'],['TTS_MODEL','模型','text'],['TTS_VOICE','声音 ID','text']]}];
function flash(value:string){toast.value=value;clearTimeout(toastTimer);toastTimer=setTimeout(()=>toast.value='',5000);}
function setTheme(value:Theme){theme.value=value;document.documentElement.dataset.theme=value;localStorage.setItem('ember-desktop-theme',value);}
async function refresh(){try{state.value=await invoke<State>('state');}catch(e:any){error.value=e.message;}}
async function act(method:RPCMethod,args:Record<string,any>={}){loading.value=true;error.value='';try{const result=await invoke(method,{instanceId:selected.value,...args});await refresh();return result;}catch(e:any){error.value=e.message;return null;}finally{loading.value=false;}}
async function enter(instance:Instance){selected.value=instance.id;tab.value='overview';room.value=null;guests.value=[];rooms.value=[];connection.value={name:instance.name,port:instance.port,lan:instance.lan,channel:instance.channel};if(instance.status==='running')await loadRooms();}
async function loadRooms(){const value=await act('rooms');if(value){rooms.value=value;if(!room.value&&value.length)await selectRoom(value[0].id);}}
async function selectRoom(roomId:string){const value=await act('room',{roomId});if(value){room.value=value;guests.value=await invoke('guestInvites',{instanceId:selected.value,roomId});}}
async function switchTab(value:string){tab.value=value;if((value==='rooms'||value==='plugins')&&running.value)await loadRooms();if(value==='settings'){const value=await act('settings');if(value){settings.value=value;changes.value={};}}if(value==='logs'){const latest=await invoke('state');logs.value=latest.tasks.filter((item:any)=>item.instance_id===selected.value).flatMap((item:any)=>item.logs||[]).slice(-160);}}
async function action(name:string){const result=await act('instanceAction',{action:name});if(result&&name==='check')flash('随安装包提供的版本：'+result.version);if(result&&name==='update')flash('正在更新至此桌面包的本体版本；数据会先备份。');}
async function createInstance(){const result=await act('createInstance',create.value);if(result){modal.value=null;await enter(result.instance);flash('正在准备独立 Python 与本体，不修改系统 PATH。');}}
async function newRoom(){const result=await act('createRoom',{title:roomTitle.value||'我们的第一夜'});if(result){roomTitle.value='';await loadRooms();await selectRoom(result.id);flash('房间已创建。下一步为同伴创建身份密钥。');}}
async function issue(){if(!room.value||!identity.value.trim())return;const result=await act('issueGuest',{roomId:room.value.id,identity:identity.value});if(result?.invite){issued.value=result.invite;modal.value='invite';identity.value='';await selectRoom(room.value.id);}}
async function revoke(invite:Invite){if(!room.value||!confirm('撤销 '+invite.identity+' 的密钥并移除入座？'))return;const result=await act('revokeGuest',{roomId:room.value.id,inviteId:invite.id});if(result){await selectRoom(room.value.id);flash('密钥已撤销，连接和角色分配已解除。');}}
async function toggle(plugin:any){if(!room.value)return;const result=await act('roomAction',{roomId:room.value.id,action:'plugin',pluginId:plugin.id,enabled:!plugin.enabled});if(result){room.value=result;flash('模块设置已更新，关闭不删除数据。');}}
async function accepting(){if(!room.value)return;const result=await act('roomAction',{roomId:room.value.id,action:'invitation',accepting:room.value.access?.accepting_players===false});if(result)room.value=result;}
async function saveSettings(){const result=await act('saveSettings',{values:changes.value});if(result){changes.value={};settings.value=await invoke('settings',{instanceId:selected.value});flash('配置已保存。启动实例后生效；密钥不会回显。');}}
async function saveConnection(){if(await act('configureInstance',connection.value))flash('网络与实例配置已保存。');}
async function copy(text:string){try{if(window.emberDesktop)await invoke('clipboard',{text});else await navigator.clipboard.writeText(text);flash('已复制');}catch{flash('自动复制不可用，请选中内容手动复制');}}
async function openGame(){if(!room.value)return;const result=await act('openGame',{roomId:room.value.id});if(result?.url)window.open(result.url,'_blank','noopener');}
onMounted(()=>{setTheme(theme.value);refresh();timer=setInterval(refresh,1800);});onUnmounted(()=>{clearInterval(timer);clearTimeout(toastTimer);});
</script>

<template>
<div class="desktop-shell">
  <header class="titlebar"><button class="brand" @click="selected=null"><span class="mark"><Flame :size="21"/></span><b>余烬桌面<span>EMBER TAVERN</span></b></button><div class="titlebar-center"><Monitor :size="15"/>房主控制台<small>0.2.0 β</small></div><div class="titlebar-right"><span class="host-badge"><ShieldCheck :size="13"/>只在房主电脑安装</span><button aria-label="打开 GitHub" @click="act('external',{url:'https://github.com/Tera-Dark/Ember-Tavern'})"><ExternalLink :size="17"/></button><button v-if="native" aria-label="最小化" @click="invoke('window',{action:'minimize'})"><Minus :size="17"/></button><button v-if="native" aria-label="关闭" @click="invoke('window',{action:'close'})"><X :size="17"/></button></div></header>
  <div v-if="error" class="error-banner"><TriangleAlert :size="17"/><span>{{error}}</span><button @click="error=''">关闭</button></div>
  <template v-if="!selected">
    <main class="home">
      <section class="home-hero"><div class="hero-symbol"><Flame :size="45" :stroke-width="1.2"/></div><div class="eyebrow">A SMALL HOST. MANY POSSIBLE WORLDS.</div><h1>把一张桌，<span>点成一个世界。</span></h1><p>你准备好酒馆，同伴只需打开浏览器入座。</p><div class="searchbox"><Search :size="18"/><input v-model="search" placeholder="搜索你的酒馆实例…" aria-label="搜索实例"/><kbd>LOCAL</kbd></div></section>
      <div class="section-line"><span><Monitor :size="15"/>我的本机实例</span><small>{{state.instances.length}} 个实例 · 数据独立保存</small></div>
      <section class="instance-grid"><button class="instance-card new-card" @click="modal='create'"><span class="plus-box"><Plus :size="27"/></span><div><h2>新建酒馆实例</h2><p>自动安装、独立环境，<br/>不用手动折腾 Python。</p></div><span class="card-link">从第一盏灯开始<ChevronRight :size="16"/></span></button>
        <article v-for="instance in filtered" :key="instance.id" class="instance-card" @click="enter(instance)" tabindex="0" @keydown.enter="enter(instance)"><div class="card-top"><span class="instance-symbol"><Monitor :size="24"/></span><span :class="['status',instance.status]"><i/>{{statusLabel[instance.status]}}</span></div><div><h2>{{instance.name}}</h2><p>{{instance.version||'随安装包提供的兼容本体'}}<br/><span>{{instance.lan?'允许 LAN 入座':'仅本机'}} · 端口 {{instance.port}}</span></p></div><div v-if="instance.task" class="mini-progress"><span :style="{width:instance.task.percent+'%'}"/></div><div class="card-link"><span>{{instance.task?.stage||'管理房间、插件与配置'}}</span><ChevronRight :size="16"/></div></article>
      </section><div class="home-note"><Users :size="20"/><div><b>朋友不需要下载 EXE。</b><p>把局域网地址、专属身份和验证密钥给同伴。房间、角色与数据都留在这台电脑。</p></div><span>一位房主，几位朋友。</span></div>
    </main>
  </template>
  <div v-else-if="active" class="instance-layout">
    <aside class="sidebar"><button class="back-button" @click="selected=null"><ArrowLeft :size="16"/>所有实例</button><div class="instance-heading"><div class="instance-symbol"><Flame :size="29"/></div><h2>{{active.name}}</h2><span :class="['status',active.status]"><i/>{{statusLabel[active.status]}}</span></div><nav><button v-for="item in tabs" :key="item.id" :class="{selected:tab===item.id}" @click="switchTab(item.id)"><component :is="item.icon" :size="18"/>{{item.name}}<ChevronRight v-if="tab===item.id" :size="14"/></button></nav><div class="sidebar-bottom"><p><ShieldCheck :size="14"/>管理权限只在本机</p><small>服务默认演示主持。真实模型与 TTS 可能收费，请只邀请可信同伴。</small></div></aside>
    <main class="workspace"><div class="workspace-top"><div><span class="eyebrow">YOUR HOST, YOUR TABLE</span><h1>{{tabs.find(item=>item.id===tab)?.name}}</h1></div><div class="row"><button class="secondary" :disabled="busy" @click="refresh"><RefreshCw :size="15"/>刷新</button><button v-if="running" class="stop-button" :disabled="busy" @click="action('stop')"><Square :size="13"/>停止实例</button><button v-else class="primary" :disabled="busy" @click="action(active.commit?'start':'install')"><component :is="busy?LoaderCircle:Play" :size="15" :class="{spin:busy}"/>{{busy?'处理中…':active.commit?'启动实例':'安装并启动'}}</button></div></div>
      <div v-if="active.task" class="task-panel"><div><LoaderCircle class="spin" :size="18"/><b>{{active.task.stage}}</b><span>{{active.task.percent}}%</span></div><div class="progress"><i :style="{width:active.task.percent+'%'}"/></div><small>安装需要网络。后台任务结束前请勿关闭桌面；更新先备份，失败会回退。</small></div>
      <template v-if="tab==='overview'"><section class="welcome-panel"><div class="welcome-icon"><Flame :size="34"/></div><div><span class="eyebrow">THE TABLE IS WAITING</span><h2>{{running?'酒馆已经亮灯。':'在这里准备下一场冒险。'}}</h2><p>一个实例是一台酒馆服务器，可保存多间冒险房间。朋友连接同一个地址，不必各自安装。</p></div></section><div class="metric-grid"><article><small>本体版本</small><b>{{active.version||'尚未安装'}}</b><span>{{active.channel==='bundled'?'随桌面包固定版本':active.channel+' 通道'}}</span></article><article><small>游戏服务端口</small><b>{{active.port}}</b><span>单 worker · {{active.lan?'允许 LAN':'仅本机'}}</span></article><article><small>运行状态</small><b>{{statusLabel[active.status]}}</b><span>{{active.pid?'进程 '+active.pid:'数据不会因停止而删除'}}</span></article></div><section class="panel"><div class="panel-title"><h3><Wifi :size="17"/>同伴的浏览器入口</h3><span class="muted">不是 localhost，也不是 0.0.0.0</span></div><div v-if="active.lan_urls.length" class="address-list"><div v-for="url in active.lan_urls" :key="url"><code>{{url}}/?guest=1</code><button @click="copy(url+'/?guest=1')"><Copy :size="15"/>复制</button></div></div><p v-else class="muted">{{active.lan?'未找到私有 IPv4 网卡。请检查 Wi-Fi／网线／VPN，再刷新。':'当前只允许本机访问，停止后到 API 与配置开启 LAN。'}}</p><p class="help-text">同伴使用你创建的身份＋专属密钥入座。系统防火墙需允许酒馆端口的私有网络访问；不会自动关闭防火墙。HTTP 不加密，远程请用 VPN／HTTPS。</p></section><div class="quick-grid"><button class="panel quick" @click="switchTab('rooms')"><Users :size="24"/><b>准备房间与身份</b><p>创建冒险，再把同伴请到桌边。</p><ChevronRight :size="17"/></button><button class="panel quick" @click="switchTab('plugins')"><Blocks :size="24"/><b>按需添加能力</b><p>地图、声音与骰盘独立开关。</p><ChevronRight :size="17"/></button></div><div class="row"><button class="secondary" :disabled="busy||!active.commit" @click="action('update')"><Download :size="15"/>应用此桌面包的本体更新</button><button class="text-button" @click="action('folder')"><FolderOpen :size="16"/>打开数据目录</button></div></template>
      <template v-if="tab==='rooms'"><div v-if="!running" class="empty"><Users :size="32"/><h3>先让酒馆亮灯。</h3><p>安装／启动实例后，房主会自动登录本机专用账号。</p></div><template v-else><section class="panel"><h3>新建冒险房间</h3><form class="inline-form" @submit.prevent="newRoom"><input v-model="roomTitle" placeholder="例如：周末 · 雾港调查" maxlength="80" aria-label="房间名称"/><button class="primary" :disabled="busy"><Plus :size="16"/>创建房间</button></form><p class="help-text">先以演示主持开始；世界书、角色和真实模型模式在冒险桌内设置。</p></section><div class="room-select"><button v-for="item in rooms" :key="item.id" :class="{selected:room?.id===item.id}" @click="selectRoom(item.id)"><BookOpen :size="16"/>{{item.title}}</button></div><section v-if="room" class="panel"><div class="panel-title"><div><span class="eyebrow">CURRENT ADVENTURE</span><h2>{{room.title}}</h2></div><button class="primary" :disabled="busy" @click="openGame"><Play :size="15"/>进入冒险桌</button></div><div class="room-summary"><span>{{room.state?.world?.title}}</span><span>{{Array.isArray(room.members)?room.members.length:room.members}} / 12 位成员</span><button class="text-button" :disabled="busy" @click="accepting">{{room.access?.accepting_players===false?'重新开放入座':'暂停新成员入座'}}</button></div><hr/><h3><KeyRound :size="17"/>同伴身份与验证密钥</h3><p class="help-text">每人一份可撤销的凭据。再次输入同一身份／密钥会回到同一位角色操控者，不需要注册账号。</p><form class="inline-form" @submit.prevent="issue"><input v-model="identity" placeholder="同伴身份，例如小王" maxlength="24" aria-label="同伴身份" required/><button class="secondary" :disabled="busy">生成专属密钥</button></form><div class="guest-row" v-for="guest in guests" :key="guest.id"><span class="identity-icon"><Users :size="15"/></span><div><b>{{guest.identity}}</b><small>{{guest.enabled?'可入座':'已撤销'}} · {{guest.user_id?'已经入座':'等待同伴'}} · {{guest.key_hint}}</small></div><button class="text-button" :disabled="busy" @click="identity=guest.identity;issue()"><RefreshCw :size="13"/>重新生成</button><button class="text-button danger" :disabled="busy||!guest.enabled" @click="revoke(guest)">撤销</button></div><p v-if="!guests.length" class="muted">还没有访客身份。密钥只生成时显示，不会在后续列表回显。</p><hr/><h3>在桌边的成员</h3><div class="members"><span v-for="member in Array.isArray(room.members)?room.members:[]" :key="member.id"><i :class="{online:member.online}"/>{{member.display_name}}<small>{{member.role==='host'?'房主':'玩家'}}</small></span></div><p class="help-text">进入冒险桌后，在角色档案分配操控者。撤销访客会断开连接并解除角色分配；不会删除故事。</p></section></template></template>
      <template v-if="tab==='plugins'"><section class="panel"><div class="panel-title"><h3><Blocks :size="18"/>扩展安装</h3><button class="secondary" :disabled="busy||running||!active.commit" @click="act('installPlugin')"><Plus :size="16"/>从本地 ZIP 安装</button></div><p class="help-text">先停止实例再安装。选择已审阅的包，确认 SHA256 与能力；Python 有完整服务器权限，不是沙箱。不会从任意 GitHub 自动下载执行。</p></section><div v-if="!running" class="empty"><Blocks :size="30"/><h3>启动后管理本房间的模块</h3><p>安装属于实例，开关属于房间；关闭不删除已有数据。</p></div><template v-else><div class="room-select"><button v-for="item in rooms" :key="item.id" :class="{selected:room?.id===item.id}" @click="selectRoom(item.id)">{{item.title}}</button></div><div v-if="!room" class="empty"><p>请先到房间与同伴创建一间房间。</p></div><div v-else class="plugins-grid"><article v-for="plugin in room.plugins" :key="plugin.id" class="panel plugin"><div class="panel-title"><Blocks :size="24"/><button class="switch" role="switch" :aria-checked="plugin.enabled" :aria-label="'开关 '+plugin.name" :disabled="busy||!!plugin.blocked" @click="toggle(plugin)"><i/></button></div><h3>{{plugin.name}}<small>v{{plugin.version}}</small></h3><p>{{plugin.description}}</p><footer><span>{{plugin.builtin?'随本体提供':'本机安装'}} · {{plugin.enabled?'本房开启':'数据保留'}}</span><code>{{plugin.id}}</code></footer><p v-if="plugin.blocked||plugin.fault" class="warning">{{plugin.blocked||plugin.fault}}</p></article></div></template></template>
      <template v-if="tab==='settings'"><div class="notice"><ShieldCheck :size="18"/><p>停止实例后才能修改运行配置。密钥不回显、不进入网页玩家端；只保存在这台房主电脑。默认演示不调用主持模型，其他模块的显式生成可独立收费。</p></div><section class="panel"><h3>实例与局域网</h3><form @submit.prevent="saveConnection" class="form"><div class="form-grid"><label>实例名称<input v-model="connection.name" :disabled="running||busy" maxlength="48"/></label><label>游戏端口<input v-model.number="connection.port" type="number" min="1024" max="65535" :disabled="running||busy"/></label></div><label class="checkbox"><input v-model="connection.lan" type="checkbox" :disabled="running||busy"/>允许同伴通过局域网浏览器入座</label><label>本体来源<select v-model="connection.channel" :disabled="running||busy"><option value="bundled">随此桌面包固定的兼容版本（推荐）</option><option value="main">GitHub main（显式信任最新源码）</option><option value="release">既有宿主 Release（可能不含桌面访客接口）</option></select></label><button class="secondary" :disabled="running||busy">保存网络与实例设置</button></form></section><section v-for="group in settingGroups" :key="group.title" class="panel"><h3>{{group.title}}</h3><p class="help-text">{{group.note}}</p><div class="form form-grid"><label v-for="field in group.fields" :key="field[0]">{{field[1]}}<span v-if="field[2]==='password'" class="configured">{{settings[field[0]+'_configured']?'已配置 · 留空不修改':'未配置'}}</span><input :type="field[2]" :value="changes[field[0]]??(field[2]==='password'?'':settings[field[0]]||'')" :disabled="running||busy" :placeholder="field[2]==='password'?'输入新密钥；不填则保留':field[0].includes('BASE_URL')?'https://api.example.com/v1':field[1]" autocomplete="off" @input="changes[field[0]]=($event.target as HTMLInputElement).value"/><button v-if="field[2]==='password'&&settings[field[0]+'_configured']" class="text-button danger" :disabled="running||busy" @click="changes[field[0]]='';flash('保存时将清除此密钥')">清除此密钥</button></label></div></section><button class="primary" :disabled="running||busy||!Object.keys(changes).length" @click="saveSettings"><Check :size="16"/>保存 API 配置</button></template>
      <template v-if="tab==='logs'"><section class="panel"><div class="panel-title"><h3>安装／运行任务日志</h3><span class="muted">供应商密钥已过滤</span></div><pre class="log-console">{{logs.length?logs.join('\n'):'还没有运行日志。启动实例后可查看任务、依赖安装和服务消息。'}}</pre></section><p class="help-text">故障时保留数据与备份，不需要删库重装。完整运行日志在本机 launcher.log；分享前仍需检查个人信息。</p></template>
    </main>
  </div>
  <footer class="desktop-footer"><span><ShieldCheck :size="13"/>本机安装 · 单服务器权威 · 同伴浏览器入座</span><div class="theme-choices"><span>外观</span><button v-for="item in ([['ember','余烬'],['moonlit','月下'],['light','浅色']] as const)" :key="item[0]" :class="['theme-dot',item[0],{active:theme===item[0]}]" :aria-label="'主题 '+item[1]" :title="item[1]" @click="setTheme(item[0])"/></div></footer>
  <div v-if="modal" class="overlay" @click.self="modal=null;issued=null"><section class="dialog" role="dialog" aria-modal="true" :aria-label="modal==='create'?'新建酒馆实例':'同伴专属密钥'"><button class="dialog-close" aria-label="关闭弹窗" @click="modal=null;issued=null"><X :size="18"/></button><span class="eyebrow">{{modal==='create'?'LIGHT YOUR FIRST EMBER':'INVITE ONE TRUSTED FRIEND'}}</span><template v-if="modal==='create'"><h2>新建酒馆实例</h2><p>首次需要网络准备专用 Python；安装失败可重试，不动系统 PATH。</p><form class="form" @submit.prevent="createInstance"><label>实例名称<input v-model="create.name" required maxlength="48" autofocus/></label><label>游戏端口<input v-model.number="create.port" type="number" min="1024" max="65535" required/></label><label class="checkbox"><input v-model="create.lan" type="checkbox"/>允许可信局域网同伴进入</label><div class="notice small"><ShieldCheck :size="17"/><p>本体随桌面包提供并固定提交版本。账号／房间／插件分别保存在独立实例，不会上传 GitHub。</p></div><button class="primary full" :disabled="loading"><component :is="loading?LoaderCircle:Download" :size="17"/>{{loading?'正在创建…':'创建、安装并启动'}}</button></form></template><template v-else-if="issued"><h2>{{issued.identity}}，你的座位已准备好。</h2><p>请把地址、身份与密钥私下发送给这一位同伴。</p><label class="secret-label">身份<input :value="issued.identity" readonly/></label><label class="secret-label">验证密钥 · 仅此一次显示<input :value="issued.verification_key" readonly @focus="($event.target as HTMLInputElement).select()"/></label><button class="primary full" @click="copy('身份：'+issued.identity+'\n验证密钥：'+issued.verification_key+'\n浏览器地址：'+(active?.lan_urls[0]?active.lan_urls[0]+'/?guest=1':'请联系房主取得 LAN 地址'))"><Copy :size="16"/>复制入座信息</button><div class="notice small"><KeyRound :size="16"/><p>密钥不在后续列表回显。丢失请重新生成；重生成立即作废旧密钥。不要把密钥放公开链接或截图。</p></div></template></section></div>
  <div v-if="toast" class="toast" role="status"><Check :size="17"/>{{toast}}<button @click="toast=''" aria-label="关闭通知"><X :size="15"/></button></div>
</div>
</template>
