const { _electron,request,expect }=require('@playwright/test');
const {mkdtempSync,rmSync,writeFileSync,readFileSync,existsSync}=require('node:fs');const {tmpdir}=require('node:os');const {join}=require('node:path');
(async()=>{const root=mkdtempSync(join(tmpdir(),'ember-desktop-qa-'));let desktop;const report={stage:'launch'};const reportPath=process.env.EMBER_SMOKE_REPORT||'desktop-smoke.json';const save=()=>{writeFileSync(reportPath,JSON.stringify(report,null,2));console.log('SMOKE_STAGE',report.stage);};const stage=s=>{report.stage=s;save();};let watchdog=setTimeout(()=>{report.status='failed';report.error='Smoke timeout';save();if(desktop)require('node:child_process').spawnSync('taskkill',['/PID',String(desktop.process().pid),'/T','/F'],{windowsHide:true});process.exit(1)},330000);save();try{
 desktop=await _electron.launch({executablePath:process.env.EMBER_SMOKE_EXE,args:[],env:{...process.env,EMBER_DESKTOP_TEST_MODE:'1',EMBER_DESKTOP_TEST_ROOT:root,EMBER_DESKTOP_TEST_PYTHON:process.env.EMBER_SMOKE_PYTHON},timeout:60000});
 stage('first_window');const page=await desktop.firstWindow({timeout:30000});const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.getByRole('heading',{name:'把一张桌，点成一个世界。'}).waitFor();
 const initial=await page.evaluate(()=>window.emberDesktop.invoke('state'));const build=initial.build;if(!build)throw new Error('Missing build provenance');Object.assign(report,{source_commit:build.commit,source_dirty:build.source_dirty,desktop_version:build.desktop_version,launcher_version:initial.launcher_version,app_version:build.app_version});
 stage('renderer_isolation');const security=await desktop.evaluate(({BrowserWindow})=>{const preferences=BrowserWindow.getAllWindows()[0].webContents.getLastWebPreferences();return {sandbox:preferences.sandbox,isolation:preferences.contextIsolation,node:preferences.nodeIntegration,security:preferences.webSecurity}});
 if(!security.sandbox||!security.isolation||security.node||!security.security)throw new Error('Renderer isolation was relaxed');report.renderer_isolated=true;
 await page.getByRole('button',{name:'主题 月下',exact:true}).click();await expect(page.locator('html')).toHaveAttribute('data-theme','moonlit');report.theme_switch=true;
 stage('bundled_install');await page.getByRole('button',{name:/新建酒馆实例/}).click();const dialog=page.getByRole('dialog');await dialog.getByLabel('实例名称',{exact:true}).fill('CI 房主桌面');await dialog.getByLabel('游戏端口',{exact:true}).fill('18180');await dialog.getByRole('button',{name:'创建、安装并启动',exact:true}).click();await expect(page.locator('.instance-heading .status')).toContainText('运行中',{timeout:120000});report.bundled_install_start=true;
 stage('room_and_guest');await page.getByRole('heading',{name:'开好第一桌，也能继续上一场。',exact:true}).waitFor();await page.locator('input[value=frontier]').check();await page.getByLabel('向导房间名称',{exact:true}).fill('桌面双端验证');await page.getByRole('button',{name:'以演示创建新房间',exact:true}).click();await page.getByRole('heading',{name:'桌面双端验证',exact:true}).waitFor();report.first_table_wizard=true;report.native_host_auto_login_and_room=true;
 await page.getByLabel('向导同伴身份',{exact:true}).fill('同伴QA');await page.getByRole('button',{name:'生成这位同伴的密钥',exact:true}).click();const key=await page.getByLabel('向导一次性显示的密钥',{exact:true}).inputValue();await page.getByRole('button',{name:'隐藏密钥',exact:true}).click();
 const guest=await request.newContext({baseURL:'http://127.0.0.1:18180'});const login=await guest.post('/api/auth/guest-join',{data:{identity:'同伴QA',verification_key:key}});if(login.status()!==200)throw new Error('Guest admission failed');const identity=await login.json();
 const state=await page.evaluate(()=>window.emberDesktop.invoke('state'));const instance=state.instances[0];const rooms=await page.evaluate(instanceId=>window.emberDesktop.invoke('rooms',{instanceId}),instance.id);const room=rooms.find(item=>item.title==='桌面双端验证');
 await page.getByLabel('分配角色 洛恩·灯誓',{exact:true}).selectOption(identity.user.id);report.wizard_character_assignment=true;
 const view=await guest.get('/api/rooms/'+room.id,{headers:{'X-Ember-Session':identity.token}});if((await view.json()).is_owner)throw new Error('Guest became host');report.named_guest_browser_only=true;
 stage('embedded_game');const gamePromise=desktop.waitForEvent('window',{timeout:30000});await page.getByRole('button',{name:'进入第一场冒险',exact:true}).click();const game=await gamePromise;await game.getByRole('button',{name:'角色档案',exact:false}).first().waitFor({timeout:30000});report.embedded_game_authenticated=true;await game.screenshot({path:reportPath+'.game.png'});await game.close();if(page.isClosed())throw new Error('Closing game destroyed its manager');report.game_close_preserves_manager=true;
 stage('local_diagnostics');await page.getByRole('button',{name:'实例概览',exact:true}).click();await page.getByRole('button',{name:'运行本机自检',exact:true}).click();await expect(page.locator('.diagnostic-list')).toContainText('本机健康检查通过');report.local_checks_no_paid_calls=true;
 stage('plugin_toggle');await page.getByRole('button',{name:'插件管理',exact:true}).click();const map=page.getByRole('switch',{name:'开关 场景地图',exact:true});await map.click();await expect(map).toHaveAttribute('aria-checked','true');report.room_plugin_toggle=true;await page.screenshot({path:reportPath+'.plugins.png'});
 stage('m1_preset_composition');await page.getByRole('button',{name:'开桌向导',exact:true}).click();await page.locator('.desktop-preset-card').filter({hasText:'小镇的一周'}).click();await page.getByLabel('玩法房间名称',{exact:true}).fill('M1 原生组合验收');await page.getByRole('button',{name:'用预设开新桌',exact:true}).click();await page.getByRole('heading',{name:'M1 原生组合验收',exact:true}).waitFor();
 const m1rooms=await page.evaluate(instanceId=>window.emberDesktop.invoke('rooms',{instanceId}),instance.id);const m1room=m1rooms.find(item=>item.title==='M1 原生组合验收');const locked=await page.evaluate(args=>window.emberDesktop.invoke('room',args),{instanceId:instance.id,roomId:m1room.id});if(locked.state.schema_version!==4||locked.state.characters.length!==4||locked.state._preset_lock.preset.id!=='town-one-week')throw new Error('Composition / version lock missing');report.preset_version_lock=true;
 const m1gamePromise=desktop.waitForEvent('window',{timeout:30000});await page.getByRole('button',{name:'进入第一场冒险',exact:true}).click();const m1game=await m1gamePromise;await m1game.getByRole('button',{name:'剧本与线索',exact:true}).click();await m1game.getByRole('button',{name:'揭示 共同布置的承诺',exact:true}).click();await m1game.getByRole('button',{name:'推进：带着想法去准备晚宴',exact:true}).click();await m1game.getByRole('button',{name:'推进：把不完美的准备带到周末',exact:true}).click();await m1game.getByRole('button',{name:'推进：兑现分担，给每个人留下位置',exact:true}).click();await expect(m1game.locator('.campaign-panel')).toContainText('已收束');report.native_scenario_ending=true;await m1game.screenshot({path:reportPath+'.m1.png'});await m1game.close();
 stage('stop_and_settings');await page.getByRole('button',{name:'停止实例',exact:true}).click();await expect(page.locator('.instance-heading .status')).toContainText('待启动',{timeout:30000});await page.getByRole('button',{name:'API 与配置',exact:true}).click();const gemini=page.getByRole('heading',{name:'世界知识 · Gemini',exact:true}).locator('..');await gemini.locator('input[type=password]').fill('qa-key-not-real');await page.getByRole('button',{name:'保存 API 配置',exact:true}).click();await expect(gemini.locator('input[type=password]')).toHaveValue('');await expect(gemini).toContainText('已配置');report.api_keys_saved_not_echoed=true;
 if(errors.length)throw new Error(errors.join('\n'));report.page_errors=[];report.status='passed';
 await guest.dispose();
 }catch(error){report.status='failed';report.error=String(error);if(desktop){const page=desktop.windows()[0];if(page&&!page.isClosed()){report.ui_error=await page.locator('.error-banner').textContent().catch(()=>null);await page.screenshot({path:reportPath+'.failure.png'}).catch(()=>{});}}throw error;}finally{save();if(existsSync(join(root,'launcher.log')))writeFileSync(reportPath+'.engine.log',readFileSync(join(root,'launcher.log')));if(desktop){await Promise.race([desktop.close(),new Promise((_,reject)=>setTimeout(()=>reject(new Error('Electron shutdown timeout')),15000))]).then(()=>{report.graceful_shutdown=true;}).catch(e=>{console.error(e);report.status='failed';report.error=String(e);process.exitCode=1;require('node:child_process').spawnSync('taskkill',['/PID',String(desktop.process().pid),'/T','/F'],{windowsHide:true});});}clearTimeout(watchdog);rmSync(root,{recursive:true,force:true});save();}
})().catch(error=>{console.error(error);process.exitCode=1});
