const { _electron,request,expect }=require('@playwright/test');
const {mkdtempSync,rmSync,writeFileSync}=require('node:fs');const {tmpdir}=require('node:os');const {join}=require('node:path');
(async()=>{const root=mkdtempSync(join(tmpdir(),'ember-desktop-qa-'));let desktop;const report={};try{
 desktop=await _electron.launch({executablePath:process.env.EMBER_SMOKE_EXE,args:[],env:{...process.env,EMBER_DESKTOP_TEST_MODE:'1',EMBER_DESKTOP_TEST_ROOT:root,EMBER_DESKTOP_TEST_PYTHON:process.env.EMBER_SMOKE_PYTHON},timeout:60000});
 const page=await desktop.firstWindow();const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.getByRole('heading',{name:'把一张桌，点成一个世界。'}).waitFor();
 const security=await desktop.evaluate(({BrowserWindow})=>{const preferences=BrowserWindow.getAllWindows()[0].webContents.getLastWebPreferences();return {sandbox:preferences.sandbox,isolation:preferences.contextIsolation,node:preferences.nodeIntegration,security:preferences.webSecurity}});
 if(!security.sandbox||!security.isolation||security.node||!security.security)throw new Error('Renderer isolation was relaxed');report.renderer_isolated=true;
 await page.getByRole('button',{name:'主题 月下',exact:true}).click();await expect(page.locator('html')).toHaveAttribute('data-theme','moonlit');report.theme_switch=true;
 await page.getByRole('button',{name:/新建酒馆实例/}).click();const dialog=page.getByRole('dialog');await dialog.getByLabel('实例名称',{exact:true}).fill('CI 房主桌面');await dialog.getByLabel('游戏端口',{exact:true}).fill('18180');await dialog.getByRole('button',{name:'创建、安装并启动',exact:true}).click();await expect(page.locator('.instance-heading .status')).toContainText('运行中',{timeout:120000});report.bundled_install_start=true;
 await page.getByRole('button',{name:'房间与同伴',exact:true}).click();await page.getByLabel('房间名称',{exact:true}).fill('桌面双端验证');await page.getByRole('button',{name:'创建房间',exact:true}).click();await page.getByRole('heading',{name:'桌面双端验证',exact:true}).waitFor();report.native_host_auto_login_and_room=true;
 await page.getByLabel('同伴身份',{exact:true}).fill('同伴QA');await page.getByRole('button',{name:'生成专属密钥',exact:true}).click();const invite=page.getByRole('dialog');const key=await invite.locator('input').nth(1).inputValue();await invite.getByRole('button',{name:'关闭弹窗'}).click();
 const guest=await request.newContext({baseURL:'http://127.0.0.1:18180'});const login=await guest.post('/api/auth/guest-join',{data:{identity:'同伴QA',verification_key:key}});if(login.status()!==200)throw new Error('Guest admission failed');const identity=await login.json();
 const state=await page.evaluate(()=>window.emberDesktop.invoke('state'));const instance=state.instances[0];const rooms=await page.evaluate(instanceId=>window.emberDesktop.invoke('rooms',{instanceId}),instance.id);const room=rooms.find(item=>item.title==='桌面双端验证');
 const view=await guest.get('/api/rooms/'+room.id,{headers:{'X-Ember-Session':identity.token}});if((await view.json()).is_owner)throw new Error('Guest became host');report.named_guest_browser_only=true;
 const gamePromise=desktop.waitForEvent('window');await page.getByRole('button',{name:'进入冒险桌',exact:true}).click();const game=await gamePromise;await game.getByRole('button',{name:'角色档案',exact:false}).first().waitFor({timeout:30000});report.embedded_game_authenticated=true;await game.close();
 await page.getByRole('button',{name:'插件管理',exact:true}).click();const map=page.getByRole('switch',{name:'开关 场景地图',exact:true});await map.click();await expect(map).toHaveAttribute('aria-checked','true');report.room_plugin_toggle=true;
 await page.getByRole('button',{name:'停止实例',exact:true}).click();await expect(page.locator('.instance-heading .status')).toContainText('待启动',{timeout:30000});await page.getByRole('button',{name:'API 与配置',exact:true}).click();const gemini=page.getByRole('heading',{name:'世界知识 · Gemini',exact:true}).locator('..');await gemini.locator('input[type=password]').fill('qa-key-not-real');await page.getByRole('button',{name:'保存 API 配置',exact:true}).click();await expect(gemini.locator('input[type=password]')).toHaveValue('');await expect(gemini).toContainText('已配置');report.api_keys_saved_not_echoed=true;
 if(errors.length)throw new Error(errors.join('\n'));report.page_errors=[];report.status='passed';
 await guest.dispose();
 }finally{if(desktop)await desktop.close();rmSync(root,{recursive:true,force:true});writeFileSync(process.env.EMBER_SMOKE_REPORT||'desktop-smoke.json',JSON.stringify(report,null,2));}
})().catch(error=>{console.error(error);process.exitCode=1});
