import React, {useState, useEffect, useRef, useCallback} from 'react';
import HostingSettings, {MODE_LABELS} from './hosting/HostingSettings';
import PresetLibrary from './presets/PresetLibrary';
import CampaignPanel from './presets/CampaignPanel';
import CampaignWorkbench from './campaign/CampaignWorkbench';
import RulesWorkbench from './rules/RulesWorkbench.jsx';
import {Flame, ArrowRight, ArrowUp, ArrowLeft, Plus, X, Check, Copy, Link, LogOut, Users, BookOpen, ScrollText, Settings2, Compass, Dices, Shield, Feather, Sword, Sparkles, Search, RotateCcw, Clock3, ChevronRight, ChevronDown, MoreHorizontal, Pencil, Trash2, Info, Download, AlertCircle, Loader2, Send, MessageCircle, Wifi, WifiOff, Sun, Moon, KeyRound, MapPin, CircleHelp, LockKeyhole, CheckCircle2, FileText, CircleDot, Puzzle, ClipboardList} from 'lucide-react';
import {PluginCenter,PluginWorkspace,PluginIcon,pluginGroups} from './PluginHost.jsx';
import {api, getToken, setToken, requestKey, downloadSession, downloadFile} from './api.js';
import {Mark, Avatar, D20, Modal, Button, Empty, Brand, avatarIcons} from './components/ui.jsx';
import {WorldPage, WorldModal} from './content/Worldbook.jsx';
import {CreatorWorkbench, ImportModal, ContextPreview} from './content/CreatorWorkbench.jsx';
import {InviteModal} from './content/RoomAccess.jsx';
import {useAppearance} from './content/appearance.js';
import './content/content.css';

const ATTRS = {strength:'力量', dexterity:'敏捷', knowledge:'学识', insight:'洞察', charisma:'魅力'};
const DND_ABILITIES = {strength:'力量', dexterity:'敏捷', constitution:'体质', intelligence:'智力', wisdom:'感知', charisma:'魅力'};
const NAV = [
  {id:'scene', label:'冒险现场', icon:Compass},
  {id:'campaign', label:'剧本与线索', icon:BookOpen},
  {id:'state', label:'战役状态', icon:ClipboardList},
  {id:'rules', label:'规则工作台', icon:Dices},
  {id:'world', label:'世界书', icon:BookOpen},
  {id:'characters', label:'角色档案', icon:Users},
  {id:'records', label:'事件档案', icon:ScrollText},
  {id:'settings', label:'主持设置', icon:Settings2},
  {id:'plugins', label:'模块中心', icon:Puzzle},
  {id:'creators', label:'创作工坊', icon:Feather}
];
const formatTime = date => new Date(date).toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit'});
const signed = n => n >= 0 ? '+' + n : String(n);

export default function App() {
  const [user,setUser] = useState(null);
  const [checking,setChecking] = useState(true);
  const [path,setPath] = useState(location.pathname);
  const [auth,setAuth] = useState(new URLSearchParams(location.search).has('guest') ? 'guest' : null);
  const [help,setHelp] = useState(false);
  const [toast,setToast] = useState(null);
  const [demoBusy,setDemoBusy] = useState(false);
  const [publicModels,setPublicModels] = useState(null);
  useEffect(()=>{api('/models').then(setPublicModels).catch(()=>{});},[]);
  const appearance = useAppearance();
  const {theme,toggleTheme} = appearance;
  const notify = useCallback((message,kind='success')=>setToast({message,kind,id:Date.now()}),[]);
  const navigate = useCallback(p=>{history.pushState({},'',p);setPath(p);},[]);
  useEffect(()=>{const pop=()=>setPath(location.pathname);window.addEventListener('popstate',pop);return()=>window.removeEventListener('popstate',pop);},[]);
  useEffect(()=>{if(toast){const t=setTimeout(()=>setToast(null),6000);return()=>clearTimeout(t);}},[toast]);
  useEffect(()=>{let alive=true;(async()=>{try{if(window.emberGame){const session=await window.emberGame.session();setToken(session.token);}if(getToken()){const who=await api('/auth/me');if(alive)setUser(who);}}catch{setToken('');}finally{if(alive)setChecking(false);}})();return()=>{alive=false;};},[]);
  useEffect(()=>{const expired=()=>{setToken('');setUser(null);notify('登录已过期，请重新登录','error');};window.addEventListener('auth-expired',expired);return()=>window.removeEventListener('auth-expired',expired);},[notify]);
  useEffect(()=>{const code=new URLSearchParams(location.search).get('join');if(user&&code){api('/rooms/join',{method:'POST',body:{code:code.toUpperCase()}}).then(r=>navigate('/room/'+r.id)).catch(e=>{notify(e.message,'error');navigate('/');});}},[user,navigate,notify]);
  const authenticated = result => {setToken(result.token);setUser(result.user);setAuth(null);if(result.room_id)navigate('/room/'+result.room_id);};
  async function demo() {setDemoBusy(true);try{authenticated(await api('/auth/demo',{method:'POST',body:{}}));}catch(e){notify(e.message,'error');}finally{setDemoBusy(false);}}
  async function logout(){try{await api('/auth/logout',{method:'POST',body:{}});}catch{}setToken('');setUser(null);navigate('/');}
  const roomId = path.startsWith('/room/') ? path.split('/')[2] : null;
  if(checking)return <div className="boot"><Mark/><Loader2 className="spin"/><span>点亮酒馆的灯…</span></div>;
  return <>
    {user&&roomId ? <Room onNavigate={navigate} key={roomId} id={roomId} user={user} onHome={()=>navigate('/')} onLogout={logout} onHelp={()=>setHelp(true)} theme={theme} appearance={appearance} toggleTheme={toggleTheme} notify={notify}/> : <>
      <header className="site-header"><div className="header-container"><Brand onClick={()=>navigate('/')}/><nav><button className="active" onClick={()=>navigate('/')}>冒险大厅</button><button onClick={()=>setHelp(true)}>关于酒馆<ArrowRight size={13}/></button></nav><div className="header-actions"><button className="icon-button" onClick={toggleTheme} aria-label="切换明暗主题">{theme==='dark'?<Sun size={18}/>:<Moon size={18}/>}</button>{user?<><span className="user-name"><span className="user-dot">{user.display_name[0]}</span>{user.display_name}</span><button className="icon-button" onClick={logout} aria-label="退出登录"><LogOut size={18}/></button></>:<><Button className="ghost" onClick={()=>setAuth('login')}>登录</Button><Button className="primary compact" onClick={()=>setAuth('register')}>加入酒馆<ArrowRight size={14}/></Button></>}</div></div></header>
      {user?<Lobby user={user} navigate={navigate} notify={notify}/>:<Landing onDemo={demo} busy={demoBusy} demoEnabled={publicModels?.demo_enabled!==false} onRegister={()=>setAuth('register')} onLogin={()=>setAuth('login')} onGuest={()=>setAuth('guest')}/>}
    </>}
    {auth==='guest'&&<GuestModal onClose={()=>setAuth(null)} onSuccess={authenticated} notify={notify}/>}
    {auth&&auth!=='guest'&&<AuthModal mode={auth} setMode={setAuth} onClose={()=>setAuth(null)} onSuccess={authenticated} notify={notify}/>}
    {help&&<HelpModal onClose={()=>setHelp(false)}/>}
    {toast&&<div className={'toast '+toast.kind} role="status">{toast.kind==='error'?<AlertCircle size={18}/>:<CheckCircle2 size={18}/>}<span>{toast.message}</span><button aria-label="关闭通知" onClick={()=>setToast(null)}><X size={15}/></button></div>}
  </>;
}

function Landing({onDemo,busy,demoEnabled,onRegister,onLogin,onGuest}) {
  return <main className="landing">
    <section className="landing-hero"><img src="/harbor.jpg" alt="薄雾笼罩的海港，酒馆的灯仍然亮着"/><div className="hero-shade"/><div className="landing-copy"><div className="eyebrow"><span className="tiny-line"/> A TABLE. A WORLD. A STORY.</div><h1>围坐一桌，<br/>走进另一个世界<span>。</span></h1><p>为故事留一盏灯。<br/>轻量的多人跑团工作台，让设定、角色与每一次选择，都有迹可循。</p><div className="hero-buttons"><Button className="primary" icon={busy?Loader2:Compass} onClick={demoEnabled?onDemo:onRegister} disabled={busy}>{busy?'正在准备冒险…':demoEnabled?'走进酒馆 · 免费试玩':'创建你的冒险'}</Button><Button className="outline" onClick={onGuest}>身份与密钥 · 受邀入座<KeyRound size={16}/></Button></div><div className="hero-note"><CircleDot size={12}/>{demoEnabled?'无密钥可体验 · 演示主持明确标注 · 随时回档':'账号保存冒险 · 双模型协作 · 随时回档'}</div></div><div className="hero-caption"><span>ADVENTURE 001</span><b>雾港 · 第十三盏灯</b><small>灯塔亮起时，不要相信渡船上的人。</small></div><span className="hero-coordinate">47° N / A STORY YET UNTOLD</span></section>
    <section className="landing-under"><div className="section-intro"><span className="eyebrow">MADE FOR YOUR NEXT SESSION</span><h2>少一点配置，多一点冒险。</h2><p>不必维护一整座工具迷宫。先让一桌人，顺利讲完一个故事。</p></div><div className="feature-row"><div className="feature"><Users/><b>一桌人，一个世界</b><p>邀请同伴加入房间，由房主分配角色。行动、骰子和状态实时同步。</p><span>01 / TOGETHER</span></div><div className="feature"><Sparkles/><b>模型协作，规则兜底</b><p>Gemini 提供世界知识，决策模型提出检定；真正的骰子由服务器掷出。</p><span>02 / GUIDED</span></div><div className="feature"><RotateCcw/><b>选择可以被重新书写</b><p>每个事件都有状态快照。回档后，废弃的未来不会再混入主持记忆。</p><span>03 / REMEMBERED</span></div></div></section>
    <footer className="site-footer"><span><Flame size={14}/> 余烬酒馆 · EMBER TAVERN</span><small>轻规则 v1 · 一个可运行的跑团 MVP</small><button onClick={onLogin}>已有账号？继续你的故事<ArrowRight size={14}/></button></footer>
  </main>;
}

function GuestModal({onClose,onSuccess,notify}) {
  const [busy,setBusy]=useState(false);
  async function submit(e){e.preventDefault();const form=new FormData(e.currentTarget);setBusy(true);try{onSuccess(await api('/auth/guest-join',{method:'POST',body:{identity:String(form.get('identity')).trim(),verification_key:String(form.get('verification_key')).trim()}}));}catch(error){notify(error.message,'error');}finally{setBusy(false);}}
  return <Modal title="同伴入座" subtitle="无需安装客户端、无需注册账号。使用房主单独给你的身份与验证密钥。" onClose={onClose}><form className="form" onSubmit={submit}><label>你的身份<input name="identity" required maxLength={24} autoComplete="nickname" placeholder="房主设置的称呼，例如小王"/></label><label>验证密钥<input name="verification_key" type="password" required minLength={24} maxLength={80} autoComplete="off" placeholder="ET- 开头的个人密钥"/></label><div className="info-box small"><LockKeyhole size={16}/><p>密钥只在这台房主服务器有效。不要贴进公开群聊；普通 LAN HTTP 不加密，公网请用 VPN／HTTPS。</p></div><Button className="primary full" type="submit" disabled={busy} icon={busy?Loader2:ArrowRight}>验证并进入房间</Button></form></Modal>;
}

function AuthModal({mode,setMode,onClose,onSuccess,notify}) {
  const [busy,setBusy]=useState(false);
  async function submit(e){e.preventDefault();const f=new FormData(e.currentTarget);setBusy(true);try{onSuccess(await api('/auth/'+(mode==='register'?'register':'login'),{method:'POST',body:{username:f.get('username'),password:f.get('password'),...(mode==='register'?{display_name:f.get('display_name')}:{})}}));}catch(e){notify(e.message,'error');}finally{setBusy(false);}}
  return <Modal title={mode==='register'?'成为酒馆的一员':'欢迎回到酒馆'} subtitle="账号用于保存房间、角色分配和冒险记录；受邀同伴请使用身份与密钥入口。" onClose={onClose}><form onSubmit={submit} className="form"><label>用户名<input name="username" autoComplete="username" required minLength={mode==='register'?3:1} maxLength={24} pattern={mode==='register'?'[A-Za-z0-9_]+':undefined} placeholder="英文、数字或下划线"/></label>{mode==='register'&&<label>桌边的称呼<input name="display_name" required maxLength={24} placeholder="大家怎么称呼你？" autoComplete="nickname"/></label>}<label>密码<input name="password" type="password" required minLength={mode==='register'?8:1} maxLength={128} autoComplete={mode==='register'?'new-password':'current-password'} placeholder={mode==='register'?'至少 8 个字符':'输入你的密码'}/></label><Button type="submit" className="primary full" icon={busy?Loader2:ArrowRight} disabled={busy}>{mode==='register'?'注册并进入大厅':'登录并继续故事'}</Button><p className="form-switch">{mode==='register'?'已经有账号？':'还没来过？'}<button type="button" onClick={()=>setMode(mode==='register'?'login':'register')}>{mode==='register'?'去登录':'创建账号'}</button></p></form></Modal>;
}

function HelpModal({onClose}) {return <Modal title="让故事发生，而不是让工具占满桌面。" subtitle="余烬酒馆 / 产品与首版边界" onClose={onClose} wide><div className="help-content"><div className="info-box"><Info size={20}/><p>当前默认是<strong>演示规则脚本</strong>，不调用 Gemini 或任何外部模型。配置服务端后，房主可明确选择真实单模型或双模型；可能产生请求费用。</p></div><h3>一场冒险的最短路径</h3><ol><li>注册账号，创建房间并选择世界预设。</li><li>桌面房主生成同伴身份与专属密钥；同伴在 LAN 浏览器入座，不必注册。备用网页登录仍可使用正式账号＋邀请码。</li><li>房主在角色档案里分配操控者。</li><li>以角色身份提交行动，主持推进故事或提出检定。</li><li>点击掷骰，服务器记录结果和属性变化。</li><li>在事件档案中检索过去；房主可回到任意有效节点。</li></ol><h3>我们先做什么，不做什么</h3><p>支持通用轻规则、角色状态、世界书、多人同步、事件快照与回档。M3 另含一条 SRD 5.2.1 有限 d20 战斗切片和一条原创合作 SLG-lite 经济样板；两者都是版本锁定的实验子集，不是完整 D&D／CoC／SLG。未实现的规则会在规则工作台明确列出；叙事文字与 AI 回复不会替代服务器命令结算。仍不包含完整战棋规则、语音会议、角色私密线索或跨房间长期记忆。</p><h3>记忆不是无限聊天记录</h3><p>主持使用当前设定、角色状态、最近事件与房间内的关键词检索。这里的检索是中文双字词/英文词项匹配，不冒充向量检索。封存的时间线不会进入当前上下文。</p><div className="help-shortcuts"><kbd>Ctrl</kbd> + <kbd>Enter</kbd> 发送行动 <span>·</span> <kbd>Esc</kbd> 关闭弹窗</div></div></Modal>;}

function Lobby({user,navigate,notify}) {
  const [rooms,setRooms]=useState(null);
  const [modal,setModal]=useState(null);
  useEffect(()=>{api('/rooms').then(setRooms).catch(e=>notify(e.message,'error'));},[notify]);
  return <main className="lobby page-container"><div className="lobby-heading"><div><span className="eyebrow">YOUR NEXT CHAPTER</span><h1>晚上好，{user.display_name}<span className="heading-dot">。</span></h1><p>有人在等一个故事。也许，就是你们的故事。</p></div><div className="lobby-actions">{user.guest_kind!=='room'&&<><Button icon={KeyRound} className="outline" onClick={()=>setModal('join')}>加入房间</Button><Button icon={Plus} className="primary" onClick={()=>setModal('create')}>创建冒险</Button></>}</div></div>
    {user.guest&&<div className="guest-note"><Info size={15}/>{user.guest_kind==='room'?'你是房主邀请的同伴。退出或换设备后，可使用原身份与验证密钥重新入座；密钥撤销后请联系房主。':'你正在使用体验账号。退出后无法通过密码找回；正式冒险请使用注册账号。'}</div>}
    <div className="lobby-featured"><img src="/harbor.jpg" alt="雾港的雨夜"/><div className="featured-shade"/><div><span className="eyebrow">A WORLD WAITING FOR YOU</span><h2>雾港 · 第十三盏灯</h2><p>一封无署名的求援信，一枚黄铜钥匙。<br/>今夜，只剩最后一班渡船。</p>{user.guest_kind!=='room'&&<button onClick={()=>setModal('create')}>以这个世界开始<ArrowRight size={16}/></button>}</div><span className="featured-stamp">轻规则<span>故事预设 01</span></span></div>
    {user.guest_kind!=='room'&&<PresetLibrary compact canImport={!user.guest} notify={notify} onCreated={room=>navigate('/room/'+room.id)}/>}<section className="rooms-section"><div className="section-title"><h2>我的冒险<span>{rooms?.length||0}</span></h2><small>你的房间与记录会保存在服务端</small></div><div className="room-grid">{rooms===null?<div className="loading-inline"><Loader2 className="spin"/>正在寻找你的桌子…</div>:rooms.map(r=><button key={r.id} className="room-card" onClick={()=>navigate('/room/'+r.id)}><div className="room-card-top"><span className="room-symbol"><Compass size={23} strokeWidth={1.3}/></span><span className={'badge '+(r.ai_mode==='demo'?'amber':'green')}>{MODE_LABELS[r.ai_mode]||'未知模式'}</span></div><h3>{r.title}</h3><p>{r.world_title}</p><div className="room-card-meta"><span><Users size={13}/>{r.members} 位成员</span><span><ScrollText size={13}/>第 {r.turn} 轮</span></div><div className="room-card-bottom"><span>{r.is_owner?'房主':'玩家'} · {r.owner_name}</span><span>继续故事<ArrowRight size={14}/></span></div></button>)}{user.guest_kind!=='room'&&<button className="room-card create-card" onClick={()=>setModal('create')}><span className="new-room-icon"><Plus size={24}/></span><h3>开启一个新故事</h3><p>一张桌子，无数种可能。</p><span className="muted">创建房间，邀请你的同伴</span></button>}</div></section>
    <footer className="lobby-footer"><Flame size={15}/><span>故事会结束，余烬仍会发光。</span><span className="mono">EMBER / V1.0</span></footer>
    {modal==='create'&&<CreateRoomModal onClose={()=>setModal(null)} onSuccess={r=>navigate('/room/'+r.id)} notify={notify}/>}{modal==='join'&&<JoinModal onClose={()=>setModal(null)} onSuccess={r=>navigate('/room/'+r.id)} notify={notify}/>}
  </main>;
}
function JoinModal({onClose,onSuccess,notify}) {
  const [busy,setBusy]=useState(false);
  async function submit(e){e.preventDefault();setBusy(true);try{onSuccess(await api('/rooms/join',{method:'POST',body:{code:new FormData(e.currentTarget).get('code').trim().toUpperCase()}}));}catch(e){notify(e.message,'error');}finally{setBusy(false);}}
  return <Modal title="桌边还有你的座位" subtitle="输入房主提供的 6 位邀请码。加入后，由房主为你分配角色。" onClose={onClose}><form className="form" onSubmit={submit}><label>房间邀请码<input className="code-input" name="code" required minLength={6} maxLength={6} autoComplete="off" placeholder="如 AB3K8R"/></label><Button className="primary full" icon={busy?Loader2:ArrowRight} disabled={busy}>加入冒险</Button></form></Modal>;
}
function CreateRoomModal({onClose,onSuccess,notify}) {
  const [preset,setPreset]=useState('harbor');const [title,setTitle]=useState('雾港的第一夜');const [busy,setBusy]=useState(false);const [models,setModels]=useState(null);const [aiMode,setAiMode]=useState('demo');
  useEffect(()=>{api('/models').then(m=>{setModels(m);if(!m.demo_enabled)setAiMode('live');}).catch(e=>notify(e.message,'error'));},[notify]);
  async function submit(e){e.preventDefault();setBusy(true);const f=new FormData(e.currentTarget);try{onSuccess(await api('/rooms',{method:'POST',body:{title,preset,premise:f.get('premise')||'',ai_mode:aiMode}}));}catch(e){notify(e.message,'error');}finally{setBusy(false);}}
  return <Modal title="为新的故事留一张桌子" subtitle="首版每间房支持最多 12 位成员。稍后可以修改世界书和角色。" onClose={onClose} wide><form className="form" onSubmit={submit}><label>冒险名称<input value={title} onChange={e=>setTitle(e.target.value)} required maxLength={60} placeholder="为这场冒险起个名字"/></label><label>选择世界</label><div className="preset-grid">{[{id:'harbor',name:'雾港 · 第十三盏灯',sub:'低魔海港 / 调查悬疑',icon:Compass},{id:'frontier',name:'余烬边境',sub:'驿路失联 / 边境冒险',icon:MapPin},{id:'custom',name:'一张空白地图',sub:'从你自己的设定出发',icon:Pencil}].map(p=><button className={'preset '+(preset===p.id?'selected':'')} type="button" key={p.id} onClick={()=>{setPreset(p.id);setTitle(p.id==='harbor'?'雾港的第一夜':p.id==='frontier'?'无声的邮差':'新的冒险');}}><p.icon size={21}/><b>{p.name}</b><small>{p.sub}</small>{preset===p.id&&<Check size={15}/>}</button>)}</div><label>{preset==='custom'?'你的世界设定':'补充设定（可选，会替换预设开场）'}<textarea name="premise" rows={4} required={preset==='custom'} maxLength={4000} placeholder="故事发生在哪里？角色们为什么聚在一起？有什么需要探索？"/></label><label>主持模式<select aria-label="新房间主持模式" value={aiMode} onChange={e=>setAiMode(e.target.value)}><option value="demo" disabled={!models?.demo_enabled}>演示规则脚本（无外部模型调用）</option><option value="single" disabled={!models?.single_ready}>真实单模型（仅决策接口，可能收费）</option><option value="live" disabled={!models?.live_ready}>真实双模型（需服务端完成配置）</option></select></label><div className="info-box small"><Info size={16}/><p>演示模式可直接验证完整流程。真实模式需正式账号和服务端密钥；单模型只需决策接口，双模型另加 Gemini。均可能收费；配置存在不代表联网或余额已验证。</p></div><div className="form-footer"><Button type="button" className="ghost" onClick={onClose}>再想一想</Button><Button className="primary" icon={busy?Loader2:Plus} disabled={busy||!models||(aiMode==='live'&&!models.live_ready)||(aiMode==='single'&&!models.single_ready)}>创建并进入房间</Button></div></form></Modal>;
}

function useRoom(id,notify) {
  const [room,setRoom]=useState(null);const [error,setError]=useState('');const [connected,setConnected]=useState(false);
  const apply = useCallback(data=>setRoom(old=>!old||data.revision>=old.revision?data:old),[]);
  const reload = useCallback(()=>api('/rooms/'+id).then(apply),[id,apply]);
  useEffect(()=>{let alive=true,ws,timer,ping,attempt=0;reload().catch(e=>{if(alive)setError(e.message);});
    function connect(){if(!alive)return;ws=new WebSocket((location.protocol==='https:'?'wss://':'ws://')+location.host+'/ws/rooms/'+id);ws.onopen=()=>{attempt=0;setConnected(true);ws.send(JSON.stringify({type:'auth',token:getToken()}));ping=setInterval(()=>{if(ws.readyState===WebSocket.OPEN)ws.send(JSON.stringify({type:'ping'}));},25000);};ws.onmessage=e=>{try{const msg=JSON.parse(e.data);if(msg.type==='state')apply(msg.data);else if(msg.type==='plugin_signal')window.dispatchEvent(new CustomEvent('ember-plugin-signal',{detail:{...msg,room_id:id}}));else if(msg.type==='plugin_error')console.warn(msg.message);}catch{}};ws.onerror=()=>setConnected(false);ws.onclose=e=>{clearInterval(ping);if(!alive)return;setConnected(false);if(e.code===4401){window.dispatchEvent(new Event('auth-expired'));return;}if(e.code===4403){setError('你已离开房间或成员资格已失效，请重新联系房主。');return;}timer=setTimeout(connect,Math.min(1000*2**attempt++,10000));};}
    const sendSignal=e=>{if(e.detail.room_id===id&&ws?.readyState===WebSocket.OPEN)ws.send(JSON.stringify(e.detail));};window.addEventListener('ember-send-plugin-signal',sendSignal);
    connect();return()=>{alive=false;window.removeEventListener('ember-send-plugin-signal',sendSignal);clearTimeout(timer);clearInterval(ping);if(ws)ws.close();};
  },[id,apply,reload]);
  useEffect(()=>{if(connected||error)return;const t=setInterval(()=>reload().catch(()=>{}),10000);return()=>clearInterval(t);},[connected,error,reload]);
  return {room,error,connected,apply,reload};
}

function Room({id,user,onNavigate,onHome,onLogout,onHelp,theme,appearance,toggleTheme,notify}) {
  const {room,error,connected,apply,reload}=useRoom(id,notify);
  const [tab,setTab]=useState('scene');const [modal,setModal]=useState(null);const [sending,setSending]=useState(false);const [partyOpen,setPartyOpen]=useState(false);
  const [input,setInput]=useState('');const [channel,setChannel]=useState('action');const [selectedChar,setSelectedChar]=useState('');
  const scrollRef=useRef(null);const bottomRef=useRef(null);const autoScroll=useRef(true);const composerRef=useRef(null);
  const busy = sending||room?.busy;
  useEffect(()=>{if(!partyOpen)return;const close=e=>{if(e.key==='Escape')setPartyOpen(false);};window.addEventListener('keydown',close);return()=>window.removeEventListener('keydown',close);},[partyOpen]);
  useEffect(()=>{if(room){const allowed=room.state.characters.filter(c=>room.is_owner||c.assigned_to===user.id);if(!allowed.some(c=>c.id===selectedChar))setSelectedChar(allowed[0]?.id||'');}},[room,selectedChar,user.id]);
  useEffect(()=>{if(tab==='scene'&&autoScroll.current)bottomRef.current?.scrollIntoView({behavior:'smooth',block:'end'});},[room?.events.length,room?.busy,tab]);
  async function mutate(endpoint,body={},method='POST',chat=false){if(!room)return null;setSending(true);try{const data=await api('/rooms/'+id+endpoint,{method,body:{...body,request_key:requestKey(),...(!chat?{expected_revision:body.expected_revision??room.revision}:{})}});apply(data);return data;}catch(e){notify(e.message,'error');if(e.status===409)await reload().catch(()=>{});return null;}finally{setSending(false);}}
  async function send(){if(!input.trim()||busy)return;const result=channel==='chat'?await mutate('/chat',{text:input},'POST',true):await mutate('/actions',{text:input,character_id:selectedChar,branch:room.branch});if(result)setInput('');}
  async function exportData(){try{await downloadSession(id);notify('事件档案已导出，包含当前和封存时间线');}catch(e){notify(e.message,'error');}}
  if(error)return <div className="room-error"><Brand onClick={onHome}/><Empty icon={LockKeyhole} title="暂时无法入座" description={error}><Button className="primary" icon={ArrowLeft} onClick={onHome}>回到大厅，用邀请码加入</Button></Empty></div>;
  if(!room)return <div className="boot"><Mark/><Loader2 className="spin"/><span>正在展开这场冒险…</span></div>;
  const chars=room.state.characters;const allowed=chars.filter(c=>room.is_owner||c.assigned_to===user.id);const check=room.state.pending_check;
  const canRoll=check&&(room.is_owner||chars.find(c=>c.id===check.character_id)?.assigned_to===user.id);
  const actionMode=room.state.action_mode||'free';const actionRound=room.state.action_round;
  const collectingRound=actionRound?.status==='collecting'?actionRound:null;
  const selectedSeat=collectingRound?.required?.find(seat=>seat.character_id===selectedChar);
  const roundAlreadySubmitted=collectingRound?.submissions?.some(item=>item.character_id===selectedChar);
  const selectedAssignment=chars.find(c=>c.id===selectedChar)?.assigned_to;
  const canSubmitNextRound=room.is_owner?(!selectedAssignment||selectedAssignment===user.id):selectedAssignment===user.id;
  const canSubmitRound=actionMode!=='round'||(collectingRound?(room.is_owner?(!selectedSeat||selectedSeat.user_id===user.id):selectedSeat?.user_id===user.id):canSubmitNextRound);
  const actionBlocked=!selectedChar||!!check||room.state.awaiting_gm||(actionMode==='round'&&(!canSubmitRound||roundAlreadySubmitted));
  const counters={world:room.state.world.lore.length,characters:chars.length,records:room.event_count,state:(room.state.campaign_state?.quests?.length||0)+(room.state.campaign_state?.npcs?.length||0)+(room.state.campaign_state?.resources?.length||0)};
  const groups=pluginGroups(room);
  const gmProvider=room.plugins.find(p=>p.enabled&&p.hooks?.includes('gm'));
  const workspaceTitle=tab==='scene'?'冒险现场':tab.startsWith('ext:')?(groups.find(g=>g.id===tab.slice(4))?.label||'扩展模块'):NAV.find(n=>n.id===tab)?.label;
  const refreshPlugins=async()=>{await api('/plugins');await reload();};
  const pluginGuide=async()=>{try{setModal({type:'pluginGuide',info:await api('/plugins/guide')});}catch(e){notify(e.message,'error');}};
  const togglePlugin=(p,enabled)=>{const affected=new Set([p.id]);let changed=true;while(changed){changed=false;for(const x of room.plugins){if(!enabled&&x.enabled&&x.requires.some(d=>affected.has(d))&&!affected.has(x.id)){affected.add(x.id);changed=true;}}}if(!enabled&&affected.size>1)setModal({type:'pluginToggle',plugin:p,enabled,affected:[...affected]});else mutate('/extensions/'+p.id+'/toggle',{enabled});};
  return <div className="room-app">
    <header className="room-header"><Brand onClick={onHome}/><div className="header-crumb"><button onClick={onHome}>冒险大厅</button><ChevronRight size={13}/><span>{room.title}</span></div><div className="room-header-actions"><span className={'connection '+(connected?'':'offline')}>{connected?<Wifi size={13}/>:<WifiOff size={13}/>}<span>{connected?'实时同步':'重连中'}</span></span><button className="icon-button" aria-label="查看队伍" onClick={()=>setPartyOpen(v=>!v)}><Users size={18}/></button><button className="icon-button" onClick={toggleTheme} aria-label="切换明暗主题">{theme==='dark'?<Sun size={18}/>:<Moon size={18}/>}</button><Button className="outline compact" icon={Link} onClick={()=>setModal({type:'invite'})}>邀请同伴</Button></div></header>
    <div className="room-body"><aside className="sidebar"><div className="sidebar-world"><div className="sidebar-cover"><img src="/harbor.jpg" alt="当前冒险的世界"/><span><Compass size={15}/>当前冒险</span></div><h2>{room.state.world.title}</h2><p><span className="status-dot"/>{room.state.game_rules?(room.state.game_rules.adapter_id==='dnd5e-srd-5.2.1/v1'?'实验规则 · SRD 5.2.1 子集':'实验规则 · 合作 SLG-lite'):room.state.campaign?.profile.checks==='narrative'?'日常叙事 · 不自动检定':'故事进行中 · 轻规则 v1'}</p></div><div className="nav-label">你的冒险桌</div><nav className="room-nav">{NAV.filter(n=>(n.id!=='campaign'||room.state.campaign)&&(n.id!=='rules'||room.state.game_rules)).map(n=><button key={n.id} className={tab===n.id?'active':''} onClick={()=>setTab(n.id)}><n.icon size={18}/><span>{n.label}</span>{counters[n.id]!==undefined&&<small>{counters[n.id]}</small>}</button>)}{groups.map(g=><button key={g.id} className={tab==='ext:'+g.id?'active':''} onClick={()=>setTab('ext:'+g.id)}><PluginIcon name={g.icon} size={18}/><span>{g.label}</span><small>插件</small></button>)}</nav><div className="sidebar-progress"><span className="nav-label">旅程刻度</span><div><Clock3 size={15}/><span>当前行动轮次</span><b>{String(room.state.turn).padStart(2,'0')}</b></div><div><RotateCcw size={15}/><span>时间线分支</span><b>{String(room.branch).padStart(2,'0')}</b></div></div><div className="sidebar-bottom"><button className="model-mini" onClick={()=>setTab('settings')}><span className="model-mini-icon"><Sparkles size={18}/></span><span><b>{!gmProvider?'人工主持':room.ai_mode==='demo'?'演示规则主持':gmProvider.name}</b><small>{!gmProvider?'主持模块关闭 · 房主补述':room.ai_mode==='demo'?'未调用外部 AI 模型':'使用已启用的主持提供者'}</small></span><ChevronRight size={14}/></button><div className="sidebar-user"><span className="user-dot">{user.display_name[0]}</span><span><b>{user.display_name}</b><small>{room.is_owner?'房主 · 可管理与回档':'玩家 · 角色操控者'}</small></span><button className="icon-button" onClick={onLogout} aria-label="退出登录"><LogOut size={15}/></button></div></div></aside>
    <main className={'workspace '+(tab==='scene'?'scene-workspace':'')}>
      <div className="workspace-header"><div><span className="eyebrow">{tab==='creators'?'CREATE, VALIDATE, SHARE':(tab==='plugins'||tab.startsWith('ext:'))?'MODULES, NOT A MONOLITH':tab==='scene'?'THE STORY UNFOLDS':tab==='world'?'THE WORLD BEHIND THE STORY':tab==='characters'?'PEOPLE MAKE THE ADVENTURE':tab==='records'?'EVERY CHOICE LEAVES A TRACE':tab==='rules'?'SERVER-AUTHORITATIVE RULES':'YOUR GAME MASTER'}</span><h1>{workspaceTitle}</h1></div><div>{tab==='scene'?<span className="badge subdued"><span className="status-dot"/>第 {room.state.turn} 轮 · {room.state.scene.title}</span>:tab==='characters'&&room.is_owner?<Button className="primary compact" icon={Plus} onClick={()=>setModal({type:'character'})}>新建角色</Button>:tab==='world'&&room.is_owner?<Button className="outline compact" icon={Pencil} onClick={()=>setModal({type:'world',expected_revision:room.revision})}>编辑世界书</Button>:tab==='records'&&room.is_owner?<Button className="outline compact" icon={Download} onClick={exportData}>导出档案</Button>:<button className="icon-button" onClick={onHelp} aria-label="查看帮助"><CircleHelp size={19}/></button>}</div></div>
      {tab==='rules'?<RulesWorkbench room={room} user={user} busy={busy} notify={notify} onCommand={(endpoint,body={},method='POST')=>mutate(endpoint,{...body,branch:room.branch},method)}/>:tab==='state'?<CampaignWorkbench room={room} busy={busy} notify={notify}
        onLedgerSave={ledger=>mutate('/campaign-state',{branch:room.branch,ledger},'PUT')}
        onModeChange={mode=>mutate('/action-mode',{branch:room.branch,mode},'PUT')}
        onSettleRound={()=>mutate('/action-round/settle',{branch:room.branch})}
        onMemorySave={body=>mutate('/memory/summary',{...body,branch:room.branch},'PUT')}/>:tab==='scene'?<>
        <div className="timeline" ref={scrollRef} onScroll={()=>{const e=scrollRef.current;autoScroll.current=e.scrollHeight-e.scrollTop-e.clientHeight<150;}}><div className="scene-banner"><img src="/harbor.jpg" alt="雾中的酒馆和码头"/><div/><section><span><MapPin size={13}/>当前场景</span><h2>{room.state.scene.title}</h2><p>{room.state.world.premise}</p></section><D20 small/></div><div className="day-divider"><span>{new Date(room.events[0]?.created_at||Date.now()).toLocaleDateString('zh-CN',{month:'long',day:'numeric'})} · 故事由此开始</span></div>
          {actionMode==='round'&&<div className="round-scene-banner"><span>小队轮次</span><b>{actionRound?.status==='collecting'?`第 ${actionRound.number} 轮 · 已提交 ${actionRound.submitted_count}/${actionRound.required_count}`:actionRound?.status==='waiting_check'?'等待本轮检定':actionRound?.status==='resolving'?'主持正在结算本轮':'等待第一位成员提交'}</b><button onClick={()=>setTab('state')}>查看行动名单<ArrowRight size={12}/></button></div>}
          {room.state.campaign&&<div className="campaign-summary"><BookOpen size={19}/><div><b>{room.state.campaign.scene_title} · {room.state.campaign.completed?'已收束':'剧本进行中'}</b><p>{room.state.campaign.objective}</p></div><Button className="outline compact" onClick={()=>setTab('campaign')}>查看本场剧本</Button></div>}
          {room.event_count>200&&<button className="load-older" onClick={()=>setTab('records')}>当前显示最近 200 条，检索或导出可查看更早记录</button>}
          <div className="events-list">{room.events.map((e,index)=><Event key={e.id} event={e} room={room} onRollback={()=>setModal({type:'rollback',event:e})} canRollback={room.is_owner&&index<room.events.length-1&&!busy}/>)}</div>
          {room.state.turn===0&&!room.state.awaiting_gm&&<div className="start-suggestions"><span><Sparkles size={13}/>从一个选择开始</span><div>{(room.state.campaign?['询问当前场景中的人','核实已经获得的线索','与同伴商量下一步']:room.state.world.title.includes('雾港')?['仔细检查黄铜钥匙','向酒保打听求援信','先去码头观察渡船']:room.state.world.title.includes('边境')?['检查黑马身上的邮袋','向驿站长打听邮差','仔细观察银色尘土']:['观察周围的环境','向在场的人打听消息','与同伴商量下一步']).map(text=><button key={text} onClick={()=>{setChannel('action');setInput('我'+text);composerRef.current?.focus();}}>{text}<ArrowRight size={11}/></button>)}</div><small>点击填入行动，你可以修改后再发送。</small></div>}
          {room.busy&&<div className="gm-thinking"><Avatar gm/><span className="thinking-dots"><i/><i/><i/></span><span>{room.ai_mode==='demo'?'演示主持正在整理这次行动…':(gmProvider?.name||'主持模块')+'正在处理这次行动…'}</span></div>}
          {room.state.awaiting_gm&&!room.busy&&!room.state.gm_error&&!room.plugins.some(p=>p.enabled&&p.hooks?.includes('gm'))&&<div className="gm-human"><Pencil size={18}/><div><b>当前使用人工主持</b><p>AI 主持模块已关闭，本轮行动和骰子已保存，等待房主补述。</p>{room.is_owner&&<Button className="outline compact" onClick={()=>setModal({type:'note'})}>写主持补述</Button>}</div></div>}
          {room.state.awaiting_gm&&!room.busy&&!room.state.gm_error&&gmProvider&&<div className="gm-human"><Sparkles size={18}/><div><b>主持模块已开启，等待继续</b><p>这一轮已保存。房主可以继续主持处理，或人工补述。</p>{room.is_owner&&<Button className="outline compact" onClick={()=>mutate('/gm/retry')}>继续主持</Button>}</div></div>}
          {room.state.gm_error&&<div className="gm-error"><AlertCircle size={19}/><div><b>主持暂时没有完成这一轮</b><p>{room.state.gm_error}</p>{room.is_owner&&<div><Button className="outline compact" icon={RotateCcw} disabled={busy} onClick={()=>mutate('/gm/retry')}>重试主持</Button><Button className="ghost compact" icon={Pencil} onClick={()=>setModal({type:'note'})}>人工补述</Button></div>}</div></div>}
          <div ref={bottomRef}/>
        </div>
        {check&&<div className="pending-check"><D20 small/><div><span className="eyebrow">等待检定 / {check.character_name}</span><h3>{ATTRS[check.attribute]}检定 <span>DC {check.dc}</span></h3><p>{check.reason}</p><small>修正 {signed(check.modifier)} · 失败代价：{check.risk==='harm'?'生命 −1':check.risk==='stress'?'压力 +1':'无属性变化'}</small></div><div><Button className="primary compact" icon={Dices} disabled={busy||!canRoll} onClick={()=>mutate('/checks/'+check.id+'/roll')}>{canRoll?'掷 d20':'等待角色操控者'}</Button>{room.is_owner&&<button className="text-button muted" disabled={busy} onClick={()=>mutate('/checks/cancel')}>取消检定</button>}</div></div>}
        <div className="composer"><div className="composer-top"><div className="channel-tabs"><button className={channel==='action'?'active':''} onClick={()=>setChannel('action')}><Feather size={14}/>角色行动</button><button className={channel==='chat'?'active':''} onClick={()=>setChannel('chat')}><MessageCircle size={14}/>场外交流</button></div>{channel==='action'&&<select className="character-select" aria-label="选择行动角色" value={selectedChar} onChange={e=>setSelectedChar(e.target.value)}>{allowed.length?allowed.map(c=><option value={c.id} key={c.id}>{c.name}</option>):<option value="">等待房主分配角色</option>}</select>}</div><div className="composer-input"><textarea ref={composerRef} aria-label={channel==='action'?'描述角色行动':'场外聊天内容'} value={input} onChange={e=>setInput(e.target.value)} rows={2} maxLength={2000} placeholder={channel==='chat'?'和桌边的同伴聊一聊（不进入主持记忆）…':!selectedChar?'请先让房主在角色档案中为你分配角色…':check?'可以先构思下一步，请完成检定后再发送…':actionMode==='round'&&roundAlreadySubmitted?'该角色已经提交本轮行动，等待房主结算或开始下一轮…':actionMode==='round'&&!canSubmitRound?'该角色本轮由其他成员操控，请选择分配给你的角色…':'你打算怎么做？描述行动，故事会作出回应…'} onKeyDown={e=>{if((e.ctrlKey||e.metaKey)&&e.key==='Enter'){e.preventDefault();if(channel==='chat'||!actionBlocked)send();}}}/><button className="send-button" aria-label="发送" disabled={busy||!input.trim()||(channel==='action'&&actionBlocked)} onClick={send}>{busy?<Loader2 size={19} className="spin"/>:<ArrowUp size={21}/>}</button></div><div className="composer-bottom"><div><button title="掷骰工具" onClick={()=>setModal({type:'dice'})}><Dices size={17}/><span>掷骰</span></button>{room.is_owner&&<button title="房主人工补述" onClick={()=>setModal({type:'note'})}><Pencil size={15}/><span>补述</span></button>}</div><small>Ctrl + Enter 发送 <span>·</span> {channel==='action'?(actionMode==='round'?'每角色本轮提交一次 · 房主决定结算':'行动进入当前时间线'):'场外内容不进入模型上下文'}</small><span className="input-length">{input.length}/2000</span></div></div>
      </>:tab==='campaign'?<div className="page-scroll"><CampaignPanel room={room} busy={busy} onReveal={clue_id=>mutate('/campaign/reveal',{scene_id:room.state.campaign.current_scene,clue_id})} onAdvance={transition_id=>mutate('/campaign/advance',{scene_id:room.state.campaign.current_scene,transition_id})} onTheme={value=>{appearance.install(value);notify('配色只应用到你的浏览器');}}/></div>:tab==='creators'?<CreatorWorkbench onPresetCreated={created=>onNavigate('/room/'+created.id)} room={room} appearance={appearance} notify={notify} onImport={kind=>setModal({type:'import',kind})}/>:tab==='plugins'?<PluginCenter room={room} onToggle={togglePlugin} onRefresh={refreshPlugins} onGuide={pluginGuide}/>:tab.startsWith('ext:')?<PluginWorkspace group={tab.slice(4)} room={room} user={user} apply={apply} reload={reload} notify={notify} theme={appearance.key}/>:tab==='world'?<WorldPage room={room} onImport={()=>setModal({type:'import',kind:'worldbook'})} onExport={()=>downloadFile('/rooms/'+id+'/content/worldbook/export','世界书-'+id.slice(0,8)+'.json').catch(e=>notify(e.message,'error'))}/>:tab==='characters'?<CharactersPage room={room} busy={busy} notify={notify} onImport={()=>setModal({type:'import',kind:'character'})} onEdit={c=>setModal({type:'character',character:c,expected_revision:room.revision})} onAssign={(c,userId)=>mutate('/characters/'+c.id+'/assign',{user_id:userId||null})}/>:tab==='records'?<RecordsPage room={room} notify={notify} busy={busy} onRollback={e=>setModal({type:'rollback',event:e})}/>:<SettingsPage room={room} busy={busy} onMode={ai_mode=>mutate('/settings',{ai_mode},'PUT')} onEnv={()=>setModal({type:'env'})} onNote={()=>setModal({type:'note'})}/>}
    </main>
    <aside className={'party-panel '+(partyOpen?'open':'')}><div className="party-heading"><h2>冒险队伍<span>{chars.length}</span></h2><div className="party-heading-actions">{partyOpen&&<button className="icon-button" aria-label="关闭队伍面板" onClick={()=>setPartyOpen(false)}><X size={18}/></button>}<button className="icon-button" aria-label="管理队伍" onClick={()=>{setTab('characters');setPartyOpen(false);}}><MoreHorizontal size={19}/></button></div></div><div className="party-scroll">{chars.map(c=><PartyCard key={c.id} char={c} members={room.members} gameRules={room.state.game_rules} onOpen={()=>{setTab('characters');setPartyOpen(false);}}/>)}<div className="party-hint"><BookOpen size={16}/><p>一个角色，一个视角。<br/>每一次选择，都在改变故事。</p></div><div className="members-heading"><span>桌边的同伴</span><small>{room.members.filter(m=>m.online).length} / {room.members.length} 在线</small></div><div className="members-list">{room.members.map(m=><div key={m.id}><span className={'member-avatar '+(m.online?'online':'')}>{m.display_name[0]}</span><span>{m.display_name}{m.id===user.id&&<small>（你）</small>}</span>{m.role==='host'?<span className="badge mini">房主</span>:<small>玩家</small>}</div>)}</div></div><div className="party-bottom"><Button className="outline full" icon={Dices} onClick={()=>setModal({type:'dice'})}>掷骰工具<span className="mono">d20</span></Button><p>随机数由服务器生成 · 可追溯</p></div></aside>
    </div>
    {partyOpen&&<button className="party-backdrop" aria-label="点击空白关闭队伍" onClick={()=>setPartyOpen(false)}/>}
    {modal?.type==='invite'&&<InviteModal room={room} user={user} busy={busy} mutate={mutate} notify={notify} onClose={()=>setModal(null)} onLeave={async()=>{setSending(true);try{await api('/rooms/'+id+'/leave',{method:'POST',body:{expected_revision:room.revision,request_key:requestKey()}});onHome();}catch(e){notify(e.message,'error');if(e.status===409)await reload();}finally{setSending(false);}}}/>}
    {modal?.type==='character'&&<CharacterModal character={modal.character} busy={busy} ruleSystem={room.state.world.rule_system} isStale={modal.expected_revision!==undefined&&modal.expected_revision!==room.revision} onClose={()=>setModal(null)} onDelete={()=>setModal({type:'deleteCharacter',character:modal.character})} onSave={async body=>{const r=await mutate('/characters'+(modal.character?'/'+modal.character.id:''),{...body,expected_revision:modal.expected_revision},modal.character?'PUT':'POST');if(r){setModal(null);notify('角色记录已保存');}}}/>}
    {modal?.type==='world'&&<WorldModal world={room.state.world} busy={busy} isStale={modal.expected_revision!==room.revision} onClose={()=>setModal(null)} onSave={async body=>{if(await mutate('/world',{...body,expected_revision:modal.expected_revision},'PUT')){setModal(null);notify('世界书已保存，并记录状态快照');}}}/>}
    {modal?.type==='dice'&&<DiceModal busy={busy} onClose={()=>setModal(null)} onRoll={async expression=>{const r=await mutate('/dice',{expression});if(r){setModal(null);setTab('scene');autoScroll.current=true;}}}/>}
    {modal?.type==='note'&&<NoteModal busy={busy} onClose={()=>setModal(null)} onSave={async body=>{if(await mutate('/gm/note',body)){setModal(null);setTab('scene');notify('房主补述已写入时间线');}}}/>}
    {modal?.type==='rollback'&&<Modal title={'回到事件 #'+modal.event.seq+' 之后？'} subtitle="这不是删除消息，而是恢复该节点的完整叙事状态。" onClose={()=>setModal(null)}><div className="form"><div className="rollback-preview"><span>{modal.event.actor_name} · {formatTime(modal.event.created_at)}</span><p>{modal.event.text}</p></div><div className="info-box warning"><RotateCcw size={18}/><p>后续事件将被封存，角色属性、物品、场景与待检定恢复到当时状态。成员和操控权限不回退。全房间将同步这一变化。</p></div><form onSubmit={async e=>{e.preventDefault();const reason=new FormData(e.currentTarget).get('reason');if(await mutate('/rollback',{target_event_id:modal.event.id,reason})){setModal(null);autoScroll.current=true;notify('已创建新的时间线，旧未来已封存');}}}><label>回档原因<input name="reason" required defaultValue="重新尝试另一种选择" maxLength={160}/></label><div className="form-footer"><Button type="button" className="ghost" onClick={()=>setModal(null)}>保留现在</Button><Button className="primary" icon={RotateCcw} disabled={busy}>确认回档</Button></div></form></div></Modal>}
    {modal?.type==='deleteCharacter'&&<Modal title={'移除「'+modal.character.name+'」？'} subtitle="将清除当前操控分配。历史记录仍保留，回档恢复角色后需重新分配。" onClose={()=>setModal(null)}><div className="form-footer"><Button className="ghost" onClick={()=>setModal(null)}>取消</Button><Button className="danger" icon={Trash2} disabled={busy} onClick={async()=>{if(await mutate('/characters/'+modal.character.id,{},'DELETE'))setModal(null);}}>确认移除</Button></div></Modal>}
    {modal?.type==='pluginToggle'&&<Modal title={'关闭「'+modal.plugin.name+'」？'} subtitle="依赖它的模块也会关闭，但历史与数据不会删除。" onClose={()=>setModal(null)}><div className="form"><p className="muted">将关闭：{modal.affected.map(id=>room.plugins.find(p=>p.id===id)?.name||id).join('、')}</p><div className="form-footer"><Button className="ghost" onClick={()=>setModal(null)}>取消</Button><Button className="primary" onClick={async()=>{if(await mutate('/extensions/'+modal.plugin.id+'/toggle',{enabled:false}))setModal(null);}}>确认关闭</Button></div></div></Modal>}
    {modal?.type==='pluginGuide'&&<Modal title="插件 SDK 与社区开发" subtitle="隔离 UI、版本化资源和显式信任的后端扩展。" onClose={()=>setModal(null)} wide><div className="help-content">{modal.info.community_url?.startsWith('https://github.com/')?<a href={modal.info.community_url} target="_blank" rel="noreferrer">打开实际配置的 GitHub 社区仓库</a>:<div className="info-box small"><Info size={17}/><p>GitHub 仓库尚未发布或配置。源码包已包含模板、CI 与贡献规范；不会伪造一个已上线的插件市场。</p></div>}<pre className="plugin-guide-text">{modal.info.text}</pre></div></Modal>}
    {modal?.type==='import'&&<ImportModal room={room} kind={modal.kind} appearance={appearance} apply={apply} reload={reload} notify={notify} onClose={()=>setModal(null)} onImported={kind=>setTab(kind==='worldbook'?'world':kind==='character'?'characters':'creators')}/>}
    {modal?.type==='env'&&<EnvModal onClose={()=>setModal(null)} notify={notify}/>}
  </div>;
}

function Event({event:e,room,onRollback,canRollback}) {
  const char=room.state.characters.find(c=>c.id===e.character_id);
  if(['system','character','world','rewind','extension','campaign_state','action_round','memory_summary'].includes(e.type))return <div className={'system-event '+(e.type==='rewind'?'rewind':'')}><span>{e.type==='rewind'?<RotateCcw size={14}/>:<CircleDot size={12}/>}</span><p>{e.text}</p><span className="event-number">#{e.seq}</span>{canRollback&&<button className="rewind-mini" title="回到此处" aria-label={'回到事件 '+e.seq} onClick={onRollback}><RotateCcw size={13}/></button>}</div>;
  if(e.type==='error')return <div className="system-event error-event"><AlertCircle size={14}/><p>{e.text}</p><span className="event-number">#{e.seq}</span></div>;
  if(e.type==='dice')return <div className={'dice-event '+(e.payload.success===false?'failure':'')}><D20 value={e.payload.kind==='check'?e.payload.rolls[0]:e.payload.total}/><div><div className="event-meta"><b>{e.payload.kind==='check'?(e.payload.character_name+' · '+ATTRS[e.payload.attribute]+'检定'):'自由掷骰'}</b><span>#{e.seq} · {formatTime(e.created_at)}</span></div><div className="dice-formula"><span>{e.payload.expression}</span><b>{e.payload.rolls.join(' + ')} {e.payload.modifier?signed(e.payload.modifier):''}<i>=</i><strong>{e.payload.total}</strong></b>{e.payload.kind==='check'&&<span className={'result '+(e.payload.success?'success':'fail')}>{e.payload.outcome} <small>/ DC {e.payload.dc}</small></span>}</div><p>{e.payload.kind==='check'?e.payload.consequence:'自由掷骰仅记录结果，不改变属性。'}</p></div>{canRollback&&<button className="rewind-mini" title="回到此处" onClick={onRollback}><RotateCcw size={14}/></button>}</div>;
  const gm=['gm','prologue','gm_note'].includes(e.type);
  return <article className={'event '+(gm?'gm-event':e.type==='chat'?'chat-event':'action-event')}><Avatar gm={gm} character={char}/><div className="event-content"><div className="event-meta"><div><b>{gm?(e.type==='gm_note'?e.actor_name+' · 房主': '余烬主持'):e.type==='chat'?e.actor_name:e.payload.character_name||char?.name||e.actor_name}</b><span className={'badge mini '+(gm?'amber':'')}>{gm?(e.type==='prologue'?'预设开场':e.type==='gm_note'?'人工补述':e.payload.mode==='demo'?'演示脚本':e.payload.mode==='single'?'单模型':e.payload.knowledge&&e.payload.decision?'双模型':'主持模块'):e.type==='chat'?'场外':'角色行动'}</span></div><span>{formatTime(e.created_at)} <span className="event-number">#{e.seq}</span></span></div><div className="event-text">{e.text}</div>{e.type==='gm'&&<details className="trace"><summary><Sparkles size={12}/>主持链路<span>{e.payload.retrieval_count} 条检索证据 · {(e.payload.duration_ms/1000).toFixed(1)}s</span><ChevronDown size={12}/></summary><div>{e.payload.mode==='demo'?<p>本条由本地演示规则脚本生成，未调用外部模型。检索使用当前房间的有效时间线。</p>:<p>主持提供者：{e.payload.label||'已启用的主持模块'}{e.payload.knowledge&&<><br/>知识顾问：{e.payload.knowledge.provider} / {e.payload.knowledge.model}</>}{e.payload.decision&&<><br/>决策模型：{e.payload.decision.model}</>}<br/>服务器校验结构化输出，骰子与状态由规则引擎执行。</p>}</div></details>}{canRollback&&<button className="event-rewind" onClick={onRollback}><RotateCcw size={12}/>回到此处</button>}</div></article>;
}
function PartyCard({char:c,members,onOpen,gameRules}) {
  const member=members.find(m=>m.id===c.assigned_to);
  const isDnd=gameRules?.adapter_id==='dnd5e-srd-5.2.1/v1';
  const isCoop=gameRules?.adapter_id==='ember-coop-settlement/v1';
  const sheet=gameRules?.sheets?.[c.id];
  return <button className="party-card" onClick={onOpen}>
    <div className="party-card-top"><Avatar character={c}/><div><h3>{c.name}</h3><p>{c.archetype}</p></div></div>
    {!isCoop&&<><div className="health-label"><span>生命 <b>{c.hp}</b><small>/{c.max_hp}</small></span><span className={c.hp===0?'danger-text':''}>{c.hp===0?'倒地':c.hp/c.max_hp<.5?'负伤':'状态稳定'}</span></div><div className="health-bar"><i style={{width:(c.hp/c.max_hp*100)+'%'}}/></div></>}
    {!isCoop&&<div className="party-attributes">{Object.entries(isDnd?DND_ABILITIES:ATTRS).map(([key,label])=><div key={key}><span>{label}</span><b>{isDnd?(sheet?.ability_scores?.[key]??'—'):signed(c.attributes[key])}</b></div>)}</div>}
    {!gameRules&&<div className="stress-row"><span>压力</span><span className="stress-pips">{Array.from({length:6},(_,i)=><i key={i} className={i<c.stress?'filled':''}/>)}</span><small>{c.stress}/6</small></div>}
    <div className="party-control"><span className={'status-dot '+(!member?'muted-dot':'')}/>{member?member.display_name+' 操控':'等待房主分配'}<ChevronRight size={12}/></div>
  </button>;
}

function CharactersPage({room,busy,onEdit,onAssign,onImport,notify}) {const dnd=room.state.game_rules?.adapter_id==='dnd5e-srd-5.2.1/v1';const coop=room.state.game_rules?.adapter_id==='ember-coop-settlement/v1';return <div className="page-scroll"><div className="info-box small"><Info size={17}/><p>{dnd?'此页维护叙事简介与物品；5e 能力值、AC、HP、休息与行动由规则工作台管理，避免直接覆盖结算。':coop?'此页维护角色叙事与物品；人物属性不会改变共享经济，所有资源与订单在规则工作台结算。':'属性与物品由房主维护，玩家只能操控被分配的角色。每位玩家最多操控一个角色；房主可代为行动和检定。'}</p></div>{room.is_owner&&<div className="content-action-bar"><Button className="outline compact" icon={Download} onClick={onImport}>导入角色卡</Button><small>标准 JSON · 新角色默认未分配 · 不导入账号或权限</small></div>}<div className="character-grid">{room.state.characters.map(c=><article className="character-card" key={c.id}><div className={'character-card-cover '+c.avatar}><Avatar character={c} size="large"/><span className="mono">CHARACTER DOSSIER</span>{room.is_owner&&<button className="icon-button" aria-label={'编辑角色 '+c.name} onClick={()=>onEdit(c)}><Pencil size={16}/></button>}</div><div className="character-card-body"><h2>{c.name}</h2><span className="character-archetype">{c.archetype}</span><p>{c.description||'这个角色的故事还未被写下。'}</p>{room.is_owner&&c.gm_notes&&<p className="gm-dossier-note"><LockKeyhole size={12}/>主持备注：{c.gm_notes}</p>}{room.is_owner&&<button className="text-button" onClick={()=>downloadFile('/rooms/'+room.id+'/content/characters/'+c.id+'/export','角色卡-'+c.id.slice(0,8)+'.json').catch(e=>notify(e.message,'error'))}><Download size={12}/>导出标准角色卡（含主持备注）</button>}{!coop&&<div className="character-stats"><div><small>生命</small><b>{c.hp}<span> / {c.max_hp}</span></b></div>{!dnd&&<div><small>压力</small><b>{c.stress}<span> / 6</span></b></div>}</div>}{dnd?<div className="full-attributes">{Object.entries(DND_ABILITIES).map(([key,label])=><div key={key}><span>{label}</span><b>{room.state.game_rules.sheets[c.id]?.ability_scores?.[key]??'—'}</b></div>)}</div>:!coop&&<div className="full-attributes">{Object.entries(ATTRS).map(([k,label])=><div key={k}><span>{label}</span><b>{signed(c.attributes[k])}</b></div>)}</div>}<div className="inventory"><span><Sword size={13}/>随身物品</span><div>{c.inventory.length?c.inventory.map((item,i)=><small key={i}>{item}</small>):<small>暂无物品</small>}</div></div><label className="assign-label"><span>角色操控者</span>{room.is_owner?<select aria-label={'分配角色 '+c.name} value={c.assigned_to||''} disabled={busy} onChange={e=>onAssign(c,e.target.value)}><option value="">未分配</option>{room.members.map(m=><option key={m.id} value={m.id}>{m.display_name}{m.role==='host'?'（房主）':''}</option>)}</select>:<b>{room.members.find(m=>m.id===c.assigned_to)?.display_name||'等待房主分配'}</b>}</label></div></article>)}</div></div>;}

function RecordsPage({room,notify,busy,onRollback}) {
  const [archived,setArchived]=useState(false);const [archiveEvents,setArchiveEvents]=useState([]);const [query,setQuery]=useState('');const [results,setResults]=useState(null);const [loading,setLoading]=useState(false);
  useEffect(()=>{if(archived)api('/rooms/'+room.id+'/events?archived=true').then(setArchiveEvents).catch(e=>notify(e.message,'error'));},[archived,room.id,room.archived_count,notify]);
  async function search(e){e.preventDefault();setLoading(true);try{const r=await api('/rooms/'+room.id+'/context?q='+encodeURIComponent(query));setResults(r);}catch(e){notify(e.message,'error');}finally{setLoading(false);}}
  const list=archived?archiveEvents:room.events.slice().reverse();
  return <div className="page-scroll"><div className="record-stats"><div><small>当前时间线</small><b>{String(room.branch).padStart(2,'0')}<span>分支</span></b></div><div><small>有效事件</small><b>{room.event_count}<span>条</span></b></div><div><small>被封存的未来</small><b>{room.archived_count}<span>条</span></b></div></div><form className="context-search" onSubmit={search}><Search size={19}/><input aria-label="检索事件与世界书" value={query} onChange={e=>setQuery(e.target.value)} maxLength={200} placeholder="检索当前时间线：钥匙、灯塔、某位角色…"/><Button className="primary compact" disabled={loading} icon={loading?Loader2:Search}>检索</Button></form><p className="search-explanation">房间内关键词检索 · 世界书 + 已确认事实 + 有效事件 · 封存事件不进入主持记忆</p>{results&&<section className="search-results"><div className="section-title"><h2>检索结果<span>{results.results.length}</span></h2><button className="text-button" onClick={()=>setResults(null)}>收起</button></div>{results.results.length?results.results.map(r=><article key={r.id}><span className={'badge mini '+(r.source==='lore'?'amber':'')}>{r.source==='lore'?'世界书':r.source==='fact'?'已确认事实':'历史事件'}</span><b>{r.title}</b><small>相关度 {r.score}</small><p>{r.text}</p></article>):<Empty icon={Search} title="没有匹配的记录" description="试试更短的关键词，或确认事件属于当前时间线。"/>}</section>}
    <div className="record-tabs"><button className={!archived?'active':''} onClick={()=>setArchived(false)}>当前时间线<span>{room.event_count}</span></button>{room.is_owner&&<button className={archived?'active':''} onClick={()=>setArchived(true)}>封存记录<span>{room.archived_count}</span></button>}<small>{archived?'仅供审计，不能直接回到封存节点':'点击回档恢复该事件发生后的完整状态'}</small></div>{list.length?<div className="record-list">{list.map((e,i)=><article key={e.id} className={archived?'archived':''}><div className="record-line"><span className="record-dot">{e.type==='rewind'?<RotateCcw size={13}/>:e.type==='dice'?<Dices size={13}/>:<ScrollText size={13}/>}</span></div><div className="record-content"><div><span className="mono">#{e.seq}</span><b>{e.actor_name}</b><span className="badge mini">{archived?'封存 · 分支 '+e.branch:{prologue:'开场',gm:'主持',action:'行动',action_intent:'轮次行动',action_round:'小队轮次',campaign_state:'战役状态',memory_summary:'主持记忆',dice:'骰子',world:'世界书',character:'角色',system:'系统',rewind:'回档',chat:'场外',gm_note:'补述',error:'错误',extension:'模块'}[e.type]}</span><small>{formatTime(e.created_at)}</small></div><p>{e.text}</p></div>{room.is_owner&&!archived&&i>0&&<button className="record-rewind" disabled={busy} onClick={()=>onRollback(e)} title="回到这个节点"><RotateCcw size={15}/><span>回档</span></button>}</article>)}</div>:<Empty icon={ScrollText} title="这里还没有记录" description={archived?'没有被封存的未来。愿每一次选择都值得。':'你的每一次行动，都会在这里留下痕迹。'}/>}<p className="record-footnote">列表最多显示最近 200 条；检索遍历有效事件，完整档案可由房主导出。</p></div>;
}

function SettingsPage(props) {return <HostingSettings {...props} contextPreview={props.room.is_owner?<ContextPreview room={props.room}/>:null}/>;}


function CharacterModal({character:c,busy,ruleSystem='ember-light/v1',isStale=false,onClose,onSave,onDelete}) {
  const m3=ruleSystem!=='ember-light/v1';
  const isDnd=ruleSystem==='dnd5e-srd-5.2.1/v1';
  const [fields,setFields]=useState(c?{name:c.name,archetype:c.archetype,description:c.description,gm_notes:c.gm_notes||'',extensions:c.extensions||{},avatar:c.avatar,hp:c.hp,max_hp:c.max_hp,stress:c.stress,attributes:{...c.attributes},inventory:c.inventory.join('\n')}:{name:'',archetype:'旅人',description:'',gm_notes:'',extensions:{},avatar:'feather',hp:12,max_hp:12,stress:0,attributes:{strength:0,dexterity:0,knowledge:0,insight:0,charisma:0},inventory:''});
  const edit=(key,value)=>setFields(f=>({...f,[key]:value}));
  return <Modal title={c?'更新角色档案':'一个新的旅人'} subtitle={isDnd?'叙事档案与 5e 规则角色卡分开；HP、AC、能力值与休息只能在规则工作台结算。':m3?'此合作经营角色卡仅用于叙事身份，不改变服务器经济规则。':'属性是检定修正值，不是 D&D 能力值。所有更改都写入事件快照。'} onClose={onClose} wide><form className="form" onSubmit={e=>{e.preventDefault();onSave({...fields,inventory:fields.inventory.split(/[\n,，]/).map(s=>s.trim()).filter(Boolean)});}}>{isStale&&<div className="info-box warning"><AlertCircle size={16}/><p>房间已更新，请关闭后重新编辑，避免覆盖新状态。未保存文字可先复制。</p></div>}<div className="avatar-picker">{Object.entries(avatarIcons).map(([key,Icon])=><button type="button" key={key} aria-label={'选择头像 '+key} className={fields.avatar===key?'selected':''} onClick={()=>edit('avatar',key)}><Icon size={25}/></button>)}</div><div className="form-grid"><label>角色姓名<input value={fields.name} onChange={e=>edit('name',e.target.value)} required maxLength={32}/></label><label>职业 / 身份<input value={fields.archetype} onChange={e=>edit('archetype',e.target.value)} required maxLength={32}/></label></div><label>人物简介<textarea aria-label="人物简介" rows={2} value={fields.description} onChange={e=>edit('description',e.target.value)} maxLength={1000}/></label><label>主持备注（仅房主可见）<textarea aria-label="主持备注（仅房主可见）" rows={2} value={fields.gm_notes} onChange={e=>edit('gm_notes',e.target.value)} maxLength={2000} placeholder="玩家端和普通插件不会收到这段备注；AI 主持可能读取"/></label>{!m3&&<><div className="form-grid three"><label>当前生命<input type="number" min={0} max={fields.max_hp} value={fields.hp} onChange={e=>edit('hp',Number(e.target.value))} required/></label><label>生命上限<input type="number" min={1} max={100} value={fields.max_hp} onChange={e=>edit('max_hp',Number(e.target.value))} required/></label><label>压力（0–6）<input type="number" min={0} max={6} value={fields.stress} onChange={e=>edit('stress',Number(e.target.value))} required/></label></div><div className="attribute-edit">{Object.entries(ATTRS).map(([key,label])=><label key={key}>{label}<input type="number" min={-3} max={5} required value={fields.attributes[key]} onChange={e=>edit('attributes',{...fields.attributes,[key]:Number(e.target.value)})}/></label>)}</div></>}<label>随身物品（每行一件，最多 24 件）<textarea value={fields.inventory} onChange={e=>edit('inventory',e.target.value)} rows={3} maxLength={1464}/></label><div className="form-footer">{c?<Button type="button" className="danger ghost" icon={Trash2} onClick={onDelete}>移除角色</Button>:<span/>}<Button className="primary" icon={Check} disabled={busy||isStale}>保存角色记录</Button></div></form></Modal>;
}
function DiceModal({busy,onClose,onRoll}) {const [expression,setExpression]=useState('1d20');return <Modal title="让命运掷一颗骰子" subtitle="自由掷骰不触发剧情或属性变化。待处理检定请使用场景中的检定卡片。" onClose={onClose}><form className="form" onSubmit={e=>{e.preventDefault();onRoll(expression);}}><div className="dice-modal-display"><D20/></div><div className="dice-presets">{['1d4','1d6','1d8','1d10','1d12','1d20','1d100'].map(d=><button className={expression===d?'selected':''} type="button" key={d} onClick={()=>setExpression(d)}>{d.slice(1)}</button>)}</div><label>骰子表达式<input value={expression} onChange={e=>setExpression(e.target.value)} required maxLength={16} placeholder="如 2d6+1、1d20+2"/></label><p className="muted form-hint">支持最多 20 颗、2–100 面骰，修正值 ±100。结果由服务端生成并写入事件。</p><Button className="primary full" icon={Dices} disabled={busy}>掷出骰子</Button></form></Modal>;}
function NoteModal({busy,onClose,onSave}) {return <Modal title="房主的声音" subtitle="可纠正主持、补充叙事或接管一次未完成的回复。不会自动更改角色属性，也不会取消已有检定。" onClose={onClose}><form className="form" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);onSave({text:f.get('text'),scene_title:f.get('scene_title')||''});}}><label>场景标题（可选）<input name="scene_title" maxLength={80} placeholder="留空则保持当前场景"/></label><label>主持补述<textarea name="text" rows={6} maxLength={4000} required placeholder="你希望桌边的玩家知道什么？"/></label><Button className="primary full" icon={Pencil} disabled={busy}>写入当前时间线</Button></form></Modal>;}
const ENV_TEXT='GEMINI_API_KEY=你的密钥\nGEMINI_MODEL=你账户可用的模型ID\nDECISION_BASE_URL=https://服务商地址/v1\nDECISION_API_KEY=你的密钥\nDECISION_MODEL=你的决策模型ID\nDECISION_JSON_MODE=true';
function EnvModal({onClose,notify}) {return <Modal title="在房主端接入真实主持" subtitle="不要将真实密钥放在浏览器、世界书或聊天里。" onClose={onClose}><div className="help-content"><ol><li>将项目根目录的 .env.example 复制为 .env。</li><li>入门只填写 DECISION 接口配置；高级双模型再填写 Gemini。模型 ID 以服务商实际可用列表为准。</li><li>停止实例后保存配置并重新启动，在「主持设置」明确选择单模型或双模型；保存和切换不主动测试付费服务。</li></ol><pre className="env-code">{ENV_TEXT}</pre><p>决策服务需兼容 POST /chat/completions。若不支持 response_format，将 DECISION_JSON_MODE 设为 false；服务端仍会严格验证 JSON 输出。</p><div className="info-box small"><Info size={16}/><p>“已配置”仅表示环境变量存在，不代表密钥已经联网验证。真实调用失败会显示具体阶段与 HTTP 状态，不会伪装成功。</p></div></div></Modal>;}
