(() => {
 const sdk=EmberSDK,root=document.getElementById('plugin-root');let ctx,lastRevision=-1;
 const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 root.innerHTML=`<style>.script-head{display:flex;gap:15px;align-items:center;justify-content:space-between;margin-bottom:18px}.script-head h2{font-size:19px;font-weight:500}.lines{display:flex;flex-direction:column;gap:13px;max-height:500px;overflow:auto;padding-right:3px}.line .row{margin-bottom:11px;justify-content:space-between}.line textarea{width:100%;min-height:92px;line-height:1.9;resize:vertical}.line input{width:140px;font-size:12px}.line .tag{font-size:10px;color:var(--gold)}.line p{white-space:pre-line;line-height:1.9;font-size:12px}.empty{border:1px dashed var(--border);padding:40px;text-align:center;color:var(--muted)}</style><div class="script-head"><div><h2>旁白与对白台本</h2><p class="note">从有效时间线分段 · 编辑只影响演绎，不改写剧情正史</p></div><button id="rebuild">从剧情重建</button></div><div class="lines" id="lines"></div>`;
 root.querySelector('#rebuild').onclick=async()=>{try{await sdk.invoke('rebuild',{});sdk.notify('台本已从当前时间线重建');}catch(e){sdk.notify(e.message,'error');}};
 sdk.onContext(c=>{ctx=c;root.querySelector('#rebuild').disabled=!c.is_owner;if(c.plugin_revision===lastRevision)return;lastRevision=c.plugin_revision;
   const lines=c.own_state.lines||[];root.querySelector('#lines').innerHTML=lines.length?lines.map((l,i)=>`<article class="card line" data-id="${l.id}"><div class="row"><span class="tag">SEGMENT ${String(i+1).padStart(2,'0')} / ${l.kind==='dialogue'?'对白':'旁白'}</span>${c.is_owner?`<input aria-label="说话者" value="${esc(l.speaker)}" maxlength="32"/><button class="save">保存片段</button>`:`<span class="badge">${esc(l.speaker)}</span>`}</div>${c.is_owner?`<textarea aria-label="台本文本" maxlength="3000">${esc(l.text)}</textarea>`:`<p>${esc(l.text)}</p>`}<p class="note">来源事件 ${l.source_event_id?esc(l.source_event_id.slice(0,8)):'当前场景'} · 随快照回档</p></article>`).join(''):'<div class="empty">还没有台本片段。开始冒险，或点击重建。</div>';
   root.querySelectorAll('.save').forEach(b=>b.onclick=async()=>{const card=b.closest('.line');try{await sdk.invoke('edit',{line_id:card.dataset.id,text:card.querySelector('textarea').value,speaker:card.querySelector('input').value});sdk.notify('片段已保存');}catch(e){sdk.notify(e.message,'error');}});
 });
})();
